from .base import *  # noqa

VALUE_DOES_NOT_MATTER_FOR_BUILD_STRING = "value-does-not-matter-for-build"

APP_ENV = "build"

SECRET_KEY = VALUE_DOES_NOT_MATTER_FOR_BUILD_STRING

ELASTICSEARCH_DSL = {
    "default": {
        "hosts": VALUE_DOES_NOT_MATTER_FOR_BUILD_STRING,
    },
}

CLAM_AV_USERNAME = VALUE_DOES_NOT_MATTER_FOR_BUILD_STRING
CLAM_AV_PASSWORD = VALUE_DOES_NOT_MATTER_FOR_BUILD_STRING
CLAM_AV_DOMAIN = VALUE_DOES_NOT_MATTER_FOR_BUILD_STRING
