# Generated by Django 3.0.7 on 2020-09-11 08:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HowDoIHome',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='PageWithTopics',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
                ('excerpt', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='PoliciesAndGuidanceHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PoliciesHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='TopicHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorkingAtDITHome',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='working_at_dit.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('working_at_dit.pagewithtopics',),
        ),
        migrations.CreateModel(
            name='HowDoI',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='working_at_dit.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('working_at_dit.pagewithtopics',),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='working_at_dit.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('working_at_dit.pagewithtopics',),
        ),
        migrations.CreateModel(
            name='TopicTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_topics', to='content.Theme')),
                ('topic', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_themes', to='working_at_dit.Topic')),
            ],
            options={
                'unique_together': {('topic', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='PageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.ContentPage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_Pages', to='working_at_dit.Topic')),
            ],
            options={
                'unique_together': {('page', 'topic')},
            },
        ),
    ]
