# Generated by Django 3.0.7 on 2020-08-13 07:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='WorkingAtDITHome',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='PageWithTopics',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
                ('topics', modelcluster.fields.ParentalManyToManyField(to='working_at_dit.Topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='TopicTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_topics', to='content.Theme')),
                ('topic', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_themes', to='working_at_dit.Topic')),
            ],
            options={
                'unique_together': {('topic', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='working_at_dit.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('working_at_dit.pagewithtopics',),
        ),
        migrations.CreateModel(
            name='GuidanceHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PoliciesHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='working_at_dit.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('working_at_dit.pagewithtopics',),
        ),
        migrations.CreateModel(
            name='PoliciesAndGuidanceHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
