# Generated by Django 3.0.7 on 2020-08-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working_at_dit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
    ]
