# Generated by Django 3.0.7 on 2021-01-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("working_at_dit", "0002_auto_20201113_0844"),
    ]

    operations = [
        migrations.AddField(
            model_name="howdoi",
            name="include_link_on_homepage",
            field=models.BooleanField(default=False),
        ),
    ]
