# Generated by Django 3.0.7 on 2020-08-13 08:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('working_at_dit', '0002_remove_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagewithtopics',
            name='topics',
        ),
        migrations.CreateModel(
            name='PageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.ContentPage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_Pages', to='working_at_dit.Topic')),
            ],
            options={
                'unique_together': {('page', 'topic')},
            },
        ),
    ]
