# Generated by Django 3.0.7 on 2020-08-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200813_1142'),
        ('working_at_dit', '0003_auto_20200813_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowDoI',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='working_at_dit.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('working_at_dit.pagewithtopics',),
        ),
        migrations.CreateModel(
            name='HowDoIHome',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
    ]
