# Generated by Django 3.2.18 on 2023-03-02 09:03

from django.db import migrations


# A migration is not the best place to perform the rebrand of "working for DIT".


class Migration(migrations.Migration):

    dependencies = [
        ("working_at_dit", "0004_auto_20210217_1343"),
    ]

    operations = []
