# Generated by Django 3.0.7 on 2020-09-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_at_dit', '0005_topichome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagewithtopics',
            name='excerpt',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
