# Generated by Django 4.1.7 on 2023-05-30 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_auto_20230209_1441"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="enable_v2_search",
        ),
        migrations.RemoveField(
            model_name="user",
            name="enable_v2_search",
        ),
    ]
