# Generated by Django 5.1.8 on 2025-04-25 11:07

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_historicaluser_enable_v2_search_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="legacy_sso_user_id",
            field=core.field_models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="legacy_sso_user_id",
            field=core.field_models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
