# Generated by Django 5.1.8 on 2025-04-25 11:07

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("country_fact_sheet", "0006_auto_20210223_0749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countryfactsheethome",
            name="group_factsheets_heading",
            field=core.field_models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Group factsheets heading",
            ),
        ),
        migrations.AlterField(
            model_name="countryfactsheethome",
            name="hmtc_region_factsheets_heading",
            field=core.field_models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="HMTC region factsheets heading",
            ),
        ),
    ]
