repos:
    - repo: https://github.com/uktrade/pii-secret-check-hooks
      rev: 0.0.0.36
      hooks:
          - id: pii_secret_filename
            files: ""
            language: python
            language_version: python3.12
            pass_filenames: true
            require_serial: true
          - id: pii_secret_file_content
            files: ""
            language: python
            language_version: python3.12
            pass_filenames: true
            require_serial: true
          - id: pii_secret_file_content_ner
            files: ""
            language: python
            language_version: python3.12
            # args: [--ner_output_file=ner_output_file.txt] # uncomment to output NER entities
            pass_filenames: true
            require_serial: true
          - id: hooks_version_check
            name: Checking local hooks against latest release
            verbose: true
            require_serial: true
    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.5.0
      hooks:
          - id: detect-secrets
            args: ["--baseline", ".secrets.baseline"]
            exclude: package.lock.json
