version: "3"
services:

  db:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=digital_workspace
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:buster
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:1.3.7
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-f",
          "http://localhost:9200/_cat/health"
        ]

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.7
    ports:
      - 5601:5601
    profiles:
      - opensearch
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch

  wagtail:
    build:
      context: .
      cache_from:
        - digital_workspace/wagtail:latest
    image: digital_workspace/wagtail:latest
    command: poetry run python manage.py runserver 0.0.0.0:8000
    # mimics production
    # command: waitress-serve --port=8000 config.wsgi:application
    volumes:
      - ./:/app/
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
      - redis
      - opensearch
      - celery
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.develeper
    stdin_open: true
    tty: true

  celery:
    image: digital_workspace/wagtail:latest
    command: poetry run celery -A config.celery worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.develeper

  celery-beat:
    image: digital_workspace/wagtail:latest
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.develeper
    volumes:
      - .:/app
    profiles:
      - celery-beat
    command: poetry run celery -A config.celery beat -l INFO
    depends_on:
      - db
      - redis

  playwright:
    build:
      context: .
      dockerfile: Dockerfile.test
      cache_from:
        - digital_workspace/playwright:latest
    image: digital_workspace/playwright:latest
    command: tail -F anything # keep running until "down" command
    volumes:
      - ./:/app/
    profiles:
      - playwright
    ipc: host
    depends_on:
      - wagtail
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.test
    links:
      - "wagtail:main"
