FROM digital_workspace/wagtail:latest

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
RUN NODE_MAJOR=18

RUN adduser pwuser

RUN poetry run playwright install-deps
RUN poetry run playwright install

RUN apt-get update
RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update
RUN apt-get install nodejs -y

RUN npm install
RUN npm run build

COPY . ./
