version: "3"
services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  opensearch:
    image: opensearchproject/opensearch:1.3.7
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-f",
          "http://localhost:9200/_cat/health"
        ]
  wagtail:
    build:
      context: .
    command: python manage.py runserver_plus 0.0.0.0:8000
    # mimics production
    # command: waitress-serve --port=8000 config.wsgi:application
    volumes:
      - ./:/app/
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
      - redis
      - opensearch
      - celery
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    stdin_open: true
    tty: true
  celery:
    build:
      context: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
  redis:
    image: redis:buster
    ports:
      - "6379:6379"
  selenium:
    image: selenium/standalone-chrome:4
    profiles:
      - selenium
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - wagtail
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.7
    ports:
      - 5601:5601
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch
