FROM digital_workspace/wagtail:latest

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN adduser pwuser

RUN poetry run playwright install-deps
RUN poetry run playwright install

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y --no-install-recommends \
    nodejs

RUN npm install
RUN npm run build

COPY . ./
