# Generated by Django 3.0.7 on 2020-11-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="featured_on_news_home",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this will cause the page to be the featured article on the news homepage. Other pages will no longer be marked as the featured article.",
            ),
        ),
    ]
