# Generated by Django 3.0.7 on 2020-09-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='excerpt',
        ),
    ]
