# Generated by Django 3.0.7 on 2020-10-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200911_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_pages', to='news.NewsPage'),
            preserve_default=False,
        ),
    ]
