# Generated by Django 3.1.6 on 2021-02-18 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_auto_20201103_0337"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newscategory",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
