# Generated by Django 3.0.7 on 2020-10-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newscategory_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='featured_on_news_home',
            field=models.BooleanField(default=False),
        ),
    ]
