# Generated by Django 3.1.6 on 2021-02-23 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_auto_20210223_0749"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_email",
            new_name="legacy_author_email",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="author_name",
            new_name="legacy_author_name",
        ),
    ]
