# Generated by Django 3.1.6 on 2021-02-28 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_auto_20210223_0842"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="posted_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
