# Generated by Django 3.1.6 on 2021-02-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_auto_20210228_0446"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
    ]
