# Generated by Django 3.1.6 on 2021-03-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_newspage_allow_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="perm_sec_as_author",
            field=models.BooleanField(default=False),
        ),
    ]
