# Generated by Django 3.1.6 on 2021-03-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_newspage_perm_sec_as_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="pinned_on_home",
            field=models.BooleanField(default=False),
        ),
    ]
