# Generated by Django 3.2.10 on 2022-01-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_historicalcomment_historicalnewscategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="result_weighting",
        ),
    ]
