# Generated by Django 3.2.17 on 2023-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_historicaldocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaldocument",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical document",
                "verbose_name_plural": "historical documents",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsitealertbanner",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical site alert banner",
                "verbose_name_plural": "historical site alert banners",
            },
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsitealertbanner",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
