version: 0.2

# env:
#   variables:

phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 16

  build:
    commands:
      - make check-fixme

  #post_build:
  #  commands:
  #    - command
