version: 0.2

# env:
#   variables:

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16

  pre_build:
    commands:
      - make check-fixme
      #- codebuild-breakpoint

  build:
    commands:
      - /work/build.sh
