# Generated by Django 4.2.16 on 2024-12-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation_prototype", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nav",
            options={},
        ),
        migrations.RemoveField(
            model_name="nav",
            name="sort_order",
        ),
    ]
