# Generated by Django 4.2.17 on 2025-01-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation_prototype", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="primarynavlink",
            options={"ordering": ["sort_order"]},
        ),
    ]
