# Generated by Django 4.2.16 on 2024-12-10 16:49

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("navigation_prototype", "0002_alter_nav_options_remove_nav_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navlink",
            name="navigation",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links",
                to="navigation_prototype.nav",
            ),
        ),
    ]
