# Generated by Django 4.2.16 on 2024-12-10 16:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("navigation_prototype", "0003_alter_navlink_navigation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryNavLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                (
                    "navigation",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="navigation_prototype.nav",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SecondaryNavLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                (
                    "parent_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_links",
                        to="navigation_prototype.primarynavlink",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="NavLink",
        ),
    ]
