# Generated by Django 4.2.16 on 2024-12-10 16:53

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("navigation_prototype", "0004_primarynavlink_secondarynavlink_delete_navlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondarynavlink",
            name="parent_link",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_links",
                to="navigation_prototype.primarynavlink",
            ),
        ),
    ]
