# Generated by Django 5.1.8 on 2025-04-25 11:10

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0004_country_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="iso_1_code",
            field=core.field_models.CharField(
                max_length=3, unique=True, verbose_name="ISO 1 Code"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="iso_2_code",
            field=core.field_models.CharField(
                max_length=2, unique=True, verbose_name="ISO 2 Code"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="iso_3_code",
            field=core.field_models.CharField(
                max_length=3, unique=True, verbose_name="ISO 3 Code"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=core.field_models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="overseas_region",
            field=core.field_models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="reference_id",
            field=core.field_models.CharField(
                max_length=11,
                primary_key=True,
                serialize=False,
                verbose_name="Reference ID",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="type",
            field=core.field_models.CharField(
                choices=[("country", "Country"), ("territory", "Territory")],
                max_length=9,
            ),
        ),
    ]
