# Generated by Django 3.0.7 on 2020-08-28 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('working_at_dit', '0005_topichome'),
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='contentpage_ptr',
        ),
        migrations.RemoveField(
            model_name='aboutushome',
            name='contentpage_ptr',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='pagewithtopics_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='working_at_dit.PageWithTopics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutushome',
            name='pagewithtopics_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='working_at_dit.PageWithTopics'),
            preserve_default=False,
        ),
    ]
