# Generated by Django 4.1.9 on 2023-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_alter_contentpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpage",
            name="body_no_html",
        ),
        migrations.AddField(
            model_name="contentpage",
            name="search_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="search_excerpt",
            field=models.CharField(
                blank=True,
                help_text="A summary of the page to be shown in search results.",
                max_length=700,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="search_headings",
            field=models.TextField(blank=True, null=True),
        ),
    ]
