# Generated by Django 4.1.9 on 2023-06-07 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0018_remove_contentpage_body_no_html_and_more"),
        ("networks", "0003_remove_network_excerpt"),
        ("working_at_dit", "0006_remove_pagewithtopics_excerpt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentpage",
            old_name="search_excerpt",
            new_name="excerpt",
        ),
    ]
