# Generated by Django 4.1.9 on 2023-07-17 09:49
import html
from django.core.exceptions import ValidationError
from django.db import migrations
from django.utils.html import strip_tags

from content.utils import truncate_words_and_chars


def fill_empty_excerpts(apps, schema_editor):
    ContentPage = apps.get_model("content", "ContentPage")
    for page in ContentPage.objects.filter(excerpt__isnull=True):
        try:
            content = "".join(
                [str(b.value) for b in page.body if b.block_type == "text_section"]
            )
            page.excerpt = truncate_words_and_chars(
                html.unescape(strip_tags(content)), 40, 700
            )
            page.save()
        except ValidationError:
            ...


def noop(apps, schema_editor): ...


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0019_rename_search_excerpt_contentpage_excerpt"),
        ("working_at_dit", "0007_guidance_content_contact_email_and_more"),
        ("networks", "0004_network_content_contact_email_network_content_owner"),
    ]

    operations = [migrations.RunPython(fill_empty_excerpts, noop)]
