# Generated by Django 4.1.10 on 2023-08-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_auto_20230717_0949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="excerpt",
            field=models.CharField(
                blank=True,
                help_text="A summary of the page to be shown in search results. (making this field empty will result in an autogenerated excerpt)",
                max_length=700,
                null=True,
            ),
        ),
    ]
