# Generated by Django 4.2.11 on 2024-05-02 08:22

import content.archived_blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_alter_contentpage_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="custom_page_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    content.archived_blocks.TitleBlock(
                                        search_index=False
                                    ),
                                ),
                                (
                                    "pages",
                                    wagtail.blocks.ListBlock(
                                        content.archived_blocks.PagePickerBlock(),
                                        search_index=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
