# Generated by Django 4.2.11 on 2024-04-29 12:17

import content.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_alter_contentpage_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link_list",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", content.blocks.TitleBlock()),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        content.blocks.PagePickerBlock()
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
