# Generated by Django 4.2.11 on 2024-05-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_alter_contentpage_excerpt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privacypolicyhome",
            name="contentpage_ptr",
        ),
        migrations.DeleteModel(
            name="PrivacyPolicy",
        ),
        migrations.DeleteModel(
            name="PrivacyPolicyHome",
        ),
    ]
