# Generated by Django 4.1.10 on 2023-10-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0117_uk_staff_locations_DIT_to_DBT"),
        ("content", "0021_alter_contentpage_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="content_contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="content_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peoplefinder.person",
            ),
        ),
    ]
