# Generated by Django 4.2.11 on 2024-05-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_contentpage_custom_page_links"),
        ("content", "0022_remove_privacypolicyhome_contentpage_ptr_and_more"),
    ]

    operations = []
