# Generated by Django 4.2.11 on 2024-05-07 13:52

import content.archived_blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0024_alter_contentpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceNavigation",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentpage",
                    ),
                ),
                (
                    "primary_content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "curated_page_links",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            content.archived_blocks.TitleBlock(
                                                search_index=False
                                            ),
                                        ),
                                        (
                                            "pages",
                                            wagtail.blocks.ListBlock(
                                                content.archived_blocks.PagePickerBlock(),
                                                search_index=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                max_length=40, required=True
                                            ),
                                        ),
                                        (
                                            "page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(required=False),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                    ),
                ),
                (
                    "secondary_content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "curated_page_links",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            content.archived_blocks.TitleBlock(
                                                search_index=False
                                            ),
                                        ),
                                        (
                                            "pages",
                                            wagtail.blocks.ListBlock(
                                                content.archived_blocks.PagePickerBlock(),
                                                search_index=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                max_length=40, required=True
                                            ),
                                        ),
                                        (
                                            "page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(required=False),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.contentpage",),
        ),
    ]
