# Generated by Django 4.2.11 on 2024-05-10 17:58

import content.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0025_servicenavigation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading2", content.blocks.Heading2Block()),
                    ("heading3", content.blocks.Heading3Block()),
                    ("heading4", content.blocks.Heading4Block()),
                    ("heading5", content.blocks.Heading5Block()),
                    (
                        "text_section",
                        content.blocks.TextBlock(
                            blank=True,
                            features=[
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                                "anchor-identifier",
                            ],
                            help_text="Some text to describe what this section is about (will be\n            displayed above the list of child pages)",
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "isdecorative",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="\n        Tick if this image is entirely decorative and does not include\n        important content. This will hide the image from users using\n        screen readers.\n        ",
                                        label="Is this a decorative image?",
                                        required=False,
                                    ),
                                ),
                                (
                                    "alt",
                                    wagtail.blocks.CharBlock(
                                        help_text="\n        Read out by screen readers or displayed if an image does not load\n        or if images have been switched off.\n\n        Unless this is a decorative image, it MUST have alt text that\n        tells people what information the image provides, describes its\n        content and function, and is specific, meaningful and concise.\n        ",
                                        label="Alt text",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="\n        Optional text displayed under the image on the page to provide\n        context.\n        ",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "embed_video",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Paste a URL from Microsoft Stream or Youtube. Please use the page URL rather than the URL from the embed code."
                                    ),
                                )
                            ],
                            help_text="Embed a video",
                        ),
                    ),
                    (
                        "media",
                        wagtail.blocks.StructBlock(
                            [("media_file", content.blocks.MediaChooserBlock())],
                            help_text="Link to a media block",
                        ),
                    ),
                    (
                        "data_table",
                        content.blocks.DataTableBlock(
                            help_text="ONLY USE THIS FOR TABLULAR DATA, NOT FOR FORMATTING"
                        ),
                    ),
                ]
            ),
        ),
    ]
