# Generated by Django 4.2.11 on 2024-05-16 09:16

import content.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0026_alter_contentpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicenavigation",
            name="primary_content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "curated_page_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    content.blocks.TitleBlock(search_index=False),
                                ),
                                (
                                    "pages",
                                    wagtail.blocks.ListBlock(
                                        content.blocks.PagePickerBlock(),
                                        search_index=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=40, required=True
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                ("url", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "navigation_card",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                ("url", wagtail.blocks.URLBlock(required=True)),
                                (
                                    "summary",
                                    wagtail.blocks.CharBlock(
                                        max_length=50, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="servicenavigation",
            name="secondary_content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "curated_page_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    content.blocks.TitleBlock(search_index=False),
                                ),
                                (
                                    "pages",
                                    wagtail.blocks.ListBlock(
                                        content.blocks.PagePickerBlock(),
                                        search_index=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=40, required=True
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                ("url", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "navigation_card",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                ("url", wagtail.blocks.URLBlock(required=True)),
                                (
                                    "summary",
                                    wagtail.blocks.CharBlock(
                                        max_length=50, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
