# Generated by Django 4.2.11 on 2024-04-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("working_at_dit", "0007_guidance_content_contact_email_and_more"),
        ("content", "0026_alter_contentpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="topics",
            field=models.ManyToManyField(
                related_name="+",
                through="working_at_dit.PageTopic",
                to="working_at_dit.topic",
            ),
        ),
    ]
