# Generated by Django 4.2.11 on 2024-05-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0121_merge_20240430_0948"),
        ("content", "0027_contentpage_topics"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndex",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.basepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.basepage",),
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentpage",
                    ),
                ),
                (
                    "content_contact_email",
                    models.EmailField(
                        help_text="Contact email shown on article, this could be the content owner or a team inbox",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "content_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="peoplefinder.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.contentpage", models.Model),
        ),
    ]
