# Generated by Django 4.2.11 on 2024-05-16 12:41

import content.archived_blocks
from django.db import migrations
import dw_design_system.dwds.components.link_list
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0029_alter_servicenavigation_secondary_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicenavigation",
            name="secondary_content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "curated_page_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    content.archived_blocks.TitleBlock(
                                        search_index=False
                                    ),
                                ),
                                (
                                    "pages",
                                    wagtail.blocks.ListBlock(
                                        content.archived_blocks.PagePickerBlock(),
                                        search_index=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=40, required=True
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                ("url", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "dw_curated_page_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    content.archived_blocks.TitleBlock(
                                        search_index=False
                                    ),
                                ),
                                (
                                    "pages",
                                    wagtail.blocks.ListBlock(
                                        content.archived_blocks.PagePickerBlock(),
                                        search_index=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "dw_cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=40, required=True
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                ("url", wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
