# Generated by Django 4.2.11 on 2024-05-16 13:38

from django.db import migrations, models
import django.db.models.deletion
import content.archived_blocks
import dw_design_system.dwds.components.link_list
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0030_alter_servicenavigation_secondary_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.basepage",
                    ),
                ),
                ("primary_elements", wagtail.fields.StreamField([], blank=True)),
                (
                    "secondary_elements",
                    wagtail.fields.StreamField(
                        [
                            (
                                "dw_curated_page_links",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            content.archived_blocks.TitleBlock(
                                                search_index=False
                                            ),
                                        ),
                                        (
                                            "pages",
                                            wagtail.blocks.ListBlock(
                                                content.archived_blocks.PagePickerBlock(),
                                                search_index=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "dw_cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                max_length=40, required=True
                                            ),
                                        ),
                                        (
                                            "page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(required=False),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.basepage",),
        ),
        migrations.DeleteModel(
            name="ServiceNavigation",
        ),
    ]
