# Generated by Django 4.2.11 on 2024-05-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0037_alter_navigationpage_primary_elements_and_more"),
        ("content", "0037_alter_navigationpage_secondary_elements"),
    ]

    operations = []
