# Generated by Django 4.2.11 on 2024-05-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0037_alter_navigationpage_secondary_elements"),
        ("content", "0038_alter_navigationpage_primary_elements_and_more"),
    ]

    operations = []
