# Generated by Django 4.2.11 on 2024-05-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0038_alter_navigationpage_primary_elements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationpage",
            name="search_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="navigationpage",
            name="search_headings",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="navigationpage",
            name="search_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
