# Generated by Django 4.2.11 on 2024-05-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0041_alter_navigationpage_primary_elements_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basepage",
            options={
                "permissions": [
                    ("view_info_page", "Can view the info page in the Wagtail admin")
                ]
            },
        ),
    ]
