# Generated by Django 4.2.15 on 2024-09-02 09:43

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0042_alter_basepage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Please use this field only to add a description for an event.",
                null=True,
                validators=[content.validators.validate_description_word_count],
            ),
        ),
    ]
