# Generated by Django 4.2.15 on 2024-08-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0042_alter_basepage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
