# Generated by Django 4.2.16 on 2024-11-18 16:36

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0043_contentpage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Describe your event in 30 words.",
                null=True,
                validators=[content.validators.validate_description_word_count],
            ),
        ),
    ]
