# Generated by Django 4.2.15 on 2024-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0043_contentpage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Please use this field only to add a description for an event.",
                max_length=70,
                null=True,
            ),
        ),
    ]
