# Generated by Django 5.1.4 on 2025-01-15 14:25

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0044_alter_contentpage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="This should not be more than 30 words.",
                null=True,
                validators=[content.validators.validate_description_word_count],
            ),
        ),
    ]
