# Generated by Django 5.1.5 on 2025-02-21 15:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0046_contentpage_useful_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="useful_links",
            field=wagtail.fields.StreamField(
                [("useful_links", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "This will be displayed on the sidebar."},
                    ),
                    1: ("wagtail.blocks.PageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("page", 1)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
