# Generated by Django 5.1.6 on 2025-03-17 21:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0048_contentpage_spotlight_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepage",
            name="page_updates",
            field=wagtail.fields.StreamField(
                [("page_update", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.DateTimeBlock", (), {}),
                    1: (
                        "peoplefinder.blocks.PersonChooserBlock",
                        (),
                        {"required": False},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("update_time", 0), ("person", 1), ("note", 2)]],
                        {},
                    ),
                },
                help_text="Tell readers about page important page changes.",
                null=True,
            ),
        ),
    ]
