# Generated by Django 5.1.7 on 2025-03-21 17:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0049_basepage_page_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading2", 0),
                    ("heading3", 1),
                    ("heading4", 2),
                    ("heading5", 3),
                    ("text_section", 4),
                    ("image", 9),
                    ("image_with_text", 11),
                    ("embed_video", 13),
                    ("media", 15),
                    ("data_table", 16),
                ],
                block_lookup={
                    0: ("content.blocks.Heading2Block", (), {}),
                    1: ("content.blocks.Heading3Block", (), {}),
                    2: ("content.blocks.Heading4Block", (), {}),
                    3: ("content.blocks.Heading5Block", (), {}),
                    4: (
                        "content.blocks.TextBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Some text to describe what this section is about (will be displayed above the list of child pages)",
                        },
                    ),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "\n        Tick if this image is entirely decorative and does not include\n        important content. This will hide the image from users using\n        screen readers.\n        ",
                            "label": "Is this a decorative image?",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\n        Read out by screen readers or displayed if an image does not load\n        or if images have been switched off.\n\n        Unless this is a decorative image, it MUST have alt text that\n        tells people what information the image provides, describes its\n        content and function, and is specific, meaningful and concise.\n        ",
                            "label": "Alt text",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\n        Optional text displayed under the image on the page to provide\n        context.\n        ",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("isdecorative", 6),
                                ("alt", 7),
                                ("caption", 8),
                            ]
                        ],
                        {},
                    ),
                    10: ("content.blocks.TextBlock", (), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("heading", 1), ("text", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Paste a URL from Microsoft Stream or Youtube. Please use the page URL rather than the URL from the embed code."
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 12)]],
                        {"help_text": "Embed a video"},
                    ),
                    14: ("content.blocks.MediaChooserBlock", (), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("media_file", 14)]],
                        {"help_text": "Link to a media block"},
                    ),
                    16: (
                        "content.blocks.DataTableBlock",
                        (),
                        {
                            "help_text": "ONLY USE THIS FOR TABLULAR DATA, NOT FOR FORMATTING"
                        },
                    ),
                },
            ),
        ),
    ]
