# Generated by Django 5.1.7 on 2025-03-24 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0049_basepage_page_updates"),
        ("peoplefinder", "0124_update_profile_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepage",
            name="page_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peoplefinder.person",
            ),
        ),
    ]
