# Generated by Django 5.1.7 on 2025-03-20 14:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0049_basepage_page_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="useful_links",
            field=wagtail.fields.StreamField(
                [("useful_links", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "This will be displayed on the sidebar."},
                    ),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("page", 1), ("url", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
