# Generated by Django 5.1.7 on 2025-03-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0050_basepage_page_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepage",
            name="page_author_name",
            field=models.CharField(
                blank=True,
                help_text="Use this to show the name of the author when there isn't an active Person to show",
                null=True,
            ),
        ),
    ]
