# Generated by Django 5.1.7 on 2025-04-09 11:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0052_alter_contentpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading2", 0),
                    ("heading3", 1),
                    ("heading4", 2),
                    ("heading5", 3),
                    ("text_section", 4),
                    ("image", 9),
                    ("image_with_text", 13),
                    ("embed_video", 15),
                    ("media", 17),
                    ("data_table", 18),
                    ("person_banner", 22),
                ],
                block_lookup={
                    0: ("content.blocks.Heading2Block", (), {}),
                    1: ("content.blocks.Heading3Block", (), {}),
                    2: ("content.blocks.Heading4Block", (), {}),
                    3: ("content.blocks.Heading5Block", (), {}),
                    4: (
                        "content.blocks.TextBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Some text to describe what this section is about (will be displayed above the list of child pages)",
                        },
                    ),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "\n        Tick if this image is entirely decorative and does not include\n        important content. This will hide the image from users using\n        screen readers.\n        ",
                            "label": "Is this a decorative image?",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\n        Read out by screen readers or displayed if an image does not load\n        or if images have been switched off.\n\n        Unless this is a decorative image, it MUST have alt text that\n        tells people what information the image provides, describes its\n        content and function, and is specific, meaningful and concise.\n        ",
                            "label": "Alt text",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\n        Optional text displayed under the image on the page to provide\n        context.\n        ",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 5),
                                ("isdecorative", 6),
                                ("alt", 7),
                                ("caption", 8),
                            ]
                        ],
                        {},
                    ),
                    10: ("content.blocks.TextBlock", (), {}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "help_text": "Position of the image relative to the text",
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\n        Optional text displayed under the image to provide context.\n        ",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 1),
                                ("text", 10),
                                ("image_position", 11),
                                ("image", 5),
                                ("image_description", 12),
                                ("image_alt", 7),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Paste a URL from Microsoft Stream or Youtube. Please use the page URL rather than the URL from the embed code."
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("video", 14)]],
                        {"help_text": "Embed a video"},
                    ),
                    16: ("content.blocks.MediaChooserBlock", (), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("media_file", 16)]],
                        {"help_text": "Link to a media block"},
                    ),
                    18: (
                        "content.blocks.DataTableBlock",
                        (),
                        {
                            "help_text": "ONLY USE THIS FOR TABLULAR DATA, NOT FOR FORMATTING"
                        },
                    ),
                    19: (
                        "peoplefinder.blocks.PersonChooserBlock",
                        (),
                        {"required": False},
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    21: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("person", 19),
                                ("person_name", 20),
                                ("person_role", 20),
                                ("person_image", 21),
                                ("secondary_image", 21),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
