# Generated by Django 5.1.8 on 2025-04-25 11:07

import content.validators
import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0054_alter_contentpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basepage",
            name="legacy_path",
            field=core.field_models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="basepage",
            name="page_author_name",
            field=core.field_models.CharField(
                blank=True,
                help_text="Use this to show the name of the author when there isn't an active Person to show",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="description",
            field=core.field_models.TextField(
                blank=True,
                help_text="This should not be more than 30 words.",
                null=True,
                validators=[content.validators.validate_description_word_count],
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="excerpt",
            field=core.field_models.CharField(
                blank=True,
                help_text="A summary of the page to be shown in search results. (making this field empty will result in an autogenerated excerpt)",
                max_length=700,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="excluded_phrases",
            field=core.field_models.CharField(
                blank=True,
                help_text="A comma separated list of excluded keywords and phrases. Do not use quotes for phrases. The page will be removed from search results for these terms",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="legacy_content",
            field=core.field_models.TextField(
                blank=True, help_text="Legacy content, pre-conversion", null=True
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="legacy_guid",
            field=core.field_models.CharField(
                blank=True, help_text="Wordpress GUID", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="pinned_phrases",
            field=core.field_models.CharField(
                blank=True,
                help_text="A comma separated list of pinned keywords and phrases. Do not use quotes for phrases. The page will be pinned to the first page of search results for these terms.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="search_content",
            field=core.field_models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="search_headings",
            field=core.field_models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="search_title",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalsearchkeywordorphrase",
            name="keyword_or_phrase",
            field=core.field_models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="historicaltheme",
            name="summary",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicaltheme",
            name="title",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="navigationpage",
            name="search_content",
            field=core.field_models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="navigationpage",
            name="search_headings",
            field=core.field_models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="navigationpage",
            name="search_title",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="searchkeywordorphrase",
            name="keyword_or_phrase",
            field=core.field_models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="theme",
            name="summary",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="theme",
            name="title",
            field=core.field_models.CharField(max_length=255),
        ),
    ]
