# Generated by Django 5.1.8 on 2025-05-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0055_alter_contentpage_body"),
        ("peoplefinder", "0128_alter_grade_options_and_update_ordering_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepage",
            name="on_behalf_of_external",
            field=models.CharField(
                blank=True,
                help_text="Enter the name of someone without an Intranet profile",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="basepage",
            name="on_behalf_of_network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="on_behalf_of",
                to="networks.network",
            ),
        ),
        migrations.AddField(
            model_name="basepage",
            name="on_behalf_of_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Select someone with a profile on the Intranet",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="on_behalf_of",
                to="peoplefinder.person",
            ),
        ),
        migrations.AddField(
            model_name="basepage",
            name="on_behalf_of_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="on_behalf_of",
                to="peoplefinder.team",
            ),
        ),
    ]
