# Generated by Django 5.1.8 on 2025-05-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0056_basepage_on_behalf_of_external_and_more"),
        ("peoplefinder", "0128_alter_grade_options_and_update_ordering_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepage",
            name="page_author_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the page author's job role. If you do not want to show a job role, choose 'Hide role'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peoplefinder.teammember",
            ),
        ),
        migrations.AddField(
            model_name="basepage",
            name="page_author_show_team",
            field=models.BooleanField(
                default=False,
                help_text="Choose this option to show the team for the selected role",
            ),
        ),
        migrations.AlterField(
            model_name="basepage",
            name="page_author",
            field=models.ForeignKey(
                blank=True,
                help_text="If no page author is selected, the page owner will be shown instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peoplefinder.person",
            ),
        ),
        migrations.AlterField(
            model_name="basepage",
            name="page_author_name",
            field=models.CharField(
                blank=True,
                help_text="If the person doesn't have an active profile on the intranet, you can manually enter their name here",
                null=True,
            ),
        ),
    ]
