# Generated by Django 5.1.8 on 2025-05-13 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0056_basepage_on_behalf_of_external_and_more"),
        ("peoplefinder", "0128_alter_grade_options_and_update_ordering_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepage",
            name="page_author_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Use this to show the role of the author",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peoplefinder.teammember",
            ),
        ),
        migrations.AddField(
            model_name="basepage",
            name="page_author_show_team",
            field=models.BooleanField(
                default=False,
                help_text="Use this to show/hide the team for the selected role",
            ),
        ),
    ]
