# Generated by Django 5.1.8 on 2025-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0057_basepage_page_author_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepage",
            name="archive_notification_sent_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="basepage",
            name="confirmed_needed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
