# Generated by Django 5.1.8 on 2025-05-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0058_basepage_archive_notification_sent_at_and_more"),
        ("peoplefinder", "0130_alter_person_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basepage",
            name="page_author",
            field=models.ForeignKey(
                blank=True,
                help_text="If the 'page author' field is empty, we will fall back to the owner of this page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peoplefinder.person",
            ),
        ),
        migrations.AlterField(
            model_name="basepage",
            name="page_author_name",
            field=models.CharField(
                blank=True,
                help_text="Use this to show the name of the author when there isn't an active Person to show",
                null=True,
            ),
        ),
    ]
