# Generated by Django 5.1.8 on 2025-05-27 11:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0058_basepage_archive_notification_sent_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorPage",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentpage",
                    ),
                ),
                (
                    "sectors",
                    wagtail.fields.StreamField(
                        [("dw_sector_card", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "content.blocks.HeadingBlock",
                                (),
                                {"max_length": 30, "required": False},
                            ),
                            1: ("wagtail.blocks.PageChooserBlock", (), {}),
                            2: (
                                "content.blocks.HeadingBlock",
                                (),
                                {
                                    "help_text": "By default, the name of the page will be the title. Override it using the below field.",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 70, "required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 1), ("title", 2), ("summary", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.StreamBlock",
                                [[("dw_navigation_card", 4)]],
                                {"label": "Sector Elements", "required": True},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("sector_title", 0), ("sector_elements", 5)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.contentpage",),
        ),
    ]
