# Generated by Django 5.1.8 on 2025-05-23 16:13

import django.db.models.deletion
import dw_design_system.dwds.components.link_list
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0058_basepage_archive_notification_sent_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.basepage",
                    ),
                ),
                ("search_title", models.CharField(max_length=255)),
                ("search_headings", models.TextField(blank=True, null=True)),
                ("search_content", models.TextField(blank=True, null=True)),
                (
                    "primary_elements",
                    wagtail.fields.StreamField(
                        [
                            ("description", 0),
                            ("dw_sector_card", 7),
                            ("dw_navigation_card", 5),
                            ("footer", 0),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("content.blocks.TextBlock", (), {}),
                            1: (
                                "content.blocks.HeadingBlock",
                                (),
                                {"max_length": 30, "required": True},
                            ),
                            2: ("wagtail.blocks.PageChooserBlock", (), {}),
                            3: (
                                "content.blocks.HeadingBlock",
                                (),
                                {
                                    "help_text": "By default, the name of the page will be the title. Override it using the below field.",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 70, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 2), ("title", 3), ("summary", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.StreamBlock",
                                [[("dw_navigation_card", 5)]],
                                {"label": "Sector Elements", "required": True},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("sector_title", 1), ("sector_elements", 6)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "secondary_elements",
                    wagtail.fields.StreamField(
                        [
                            ("dw_curated_page_links", 4),
                            ("dw_tagged_page_list", 7),
                            ("dw_cta", 11),
                            ("dw_engagement_card", 13),
                            ("dw_navigation_card", 16),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "content.blocks.HeadingBlock",
                                (),
                                {
                                    "form_classname": "full title",
                                    "icon": "title",
                                    "label": "Title",
                                    "max_length": 30,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 70, "required": False},
                            ),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page"},
                            ),
                            3: ("wagtail.blocks.ListBlock", (2,), {}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("pages", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": dw_design_system.dwds.components.link_list.get_tag_choices,
                                    "label": "Tag",
                                },
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": dw_design_system.dwds.components.link_list.get_ordering_choices,
                                    "label": "Ordering",
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("tag", 5),
                                        ("ordering_choice", 6),
                                    ]
                                ],
                                {},
                            ),
                            8: (
                                "content.blocks.HeadingBlock",
                                (),
                                {"max_length": 30, "required": True},
                            ),
                            9: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            10: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 8),
                                        ("description", 1),
                                        ("page", 9),
                                        ("url", 10),
                                    ]
                                ],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["content.ContentPage"]},
                            ),
                            13: ("wagtail.blocks.StructBlock", [[("page", 12)]], {}),
                            14: ("wagtail.blocks.PageChooserBlock", (), {}),
                            15: (
                                "content.blocks.HeadingBlock",
                                (),
                                {
                                    "help_text": "By default, the name of the page will be the title. Override it using the below field.",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 14), ("title", 15), ("summary", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.basepage", models.Model),
        ),
    ]
