# Generated by Django 4.1.9 on 2023-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="'Flat key' of the setting", max_length=200
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, help_text="Setting value", max_length=200, null=True
                    ),
                ),
            ],
        ),
    ]
