# Generated by Django 4.2.16 on 2024-11-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extended_search", "0002_alter_setting_options_alter_setting_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="setting",
            options={
                "permissions": (
                    ("view_explore", "View the global search explore page"),
                    ("export_search", "Export the search result as csv"),
                )
            },
        ),
    ]
