# Generated by Django 5.1.8 on 2025-04-25 11:10

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extended_search", "0003_alter_setting_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="key",
            field=core.field_models.CharField(
                help_text="'Flat key' of the setting", max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="value",
            field=core.field_models.CharField(
                blank=True, help_text="Setting value", max_length=200, null=True
            ),
        ),
    ]
