# Generated by Django 4.2.11 on 2024-05-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0036_contentpage_new_preview_image"),
        ("news", "0013_auto_20230209_1441"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="preview_image",
        ),
    ]
