# Generated by Django 4.2.14 on 2024-08-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_remove_newspage_preview_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="news_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="news.newspage",
            ),
        ),
    ]
