# Generated by Django 4.2.15 on 2024-08-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0042_alter_basepage_options"),
        ("news", "0015_alter_comment_news_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="news_page",
            new_name="page",
        ),
        migrations.AlterField(
            model_name="comment",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="content.contentpage",
            ),
        ),
        migrations.RenameField(
            model_name="historicalcomment",
            old_name="news_page",
            new_name="page",
        ),
        migrations.AlterField(
            model_name="historicalcomment",
            name="page",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentpage",
            ),
        ),
    ]
