# Generated by Django 4.2.15 on 2024-10-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0016_alter_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="featured_on_news_home",
        ),
    ]
