# Generated by Django 5.1.5 on 2025-02-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0017_remove_newspage_featured_on_news_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="allow_reactions",
            field=models.BooleanField(default=True),
        ),
    ]
