# Generated by Django 5.1.7 on 2025-03-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0018_newspage_allow_reactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
