# Generated by Django 5.1.5 on 2025-03-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0019_comment_is_visible_historicalcomment_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="edited_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
