# Generated by Django 5.1.8 on 2025-04-25 11:07

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0021_alter_newspage_perm_sec_as_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=core.field_models.TextField(),
        ),
        migrations.AlterField(
            model_name="comment",
            name="legacy_author_name",
            field=core.field_models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcomment",
            name="content",
            field=core.field_models.TextField(),
        ),
        migrations.AlterField(
            model_name="historicalcomment",
            name="legacy_author_name",
            field=core.field_models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalnewscategory",
            name="category",
            field=core.field_models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="newscategory",
            name="category",
            field=core.field_models.CharField(max_length=255, unique=True),
        ),
    ]
