# Generated by Django 4.2.15 on 2024-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_homeprioritypage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="ribbon_text",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
