# Generated by Django 4.2.14 on 2024-09-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("home", "0007_homeprioritypage_ribbon_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homeprioritypage",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="homeprioritypage",
            unique_together={("home_page", "page")},
        ),
    ]
