# Generated by Django 4.2.15 on 2024-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_homepage_ribbon_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="ribbon_text",
        ),
        migrations.AddField(
            model_name="homeprioritypage",
            name="ribbon_text",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
