# Generated by Django 4.2.15 on 2024-09-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_homepage_ribbon_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeprioritypage",
            name="ribbon_text",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
