# Generated by Django 4.2.15 on 2024-09-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_homeprioritypage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="priority_pages_layout",
            field=models.CharField(
                choices=[
                    ("L1_0", "1 card"),
                    ("L2_0", "2 cards"),
                    ("L3_0", "3 cards"),
                    ("L1_2", "1 card then 2 cards"),
                    ("L1_3", "1 card then 3 cards"),
                    ("L2_3", "2 cards then 3 cards"),
                ],
                default="L1_3",
                max_length=4,
            ),
        ),
    ]
