# Generated by Django 4.2.15 on 2024-09-05 10:10

from django.db import migrations, models
import django.db.models.deletion
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("home", "0009_alter_homeprioritypage_ribbon_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeprioritypage",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priority_page",
                to="wagtailcore.page",
                validators=[home.validators.validate_home_priority_pages],
            ),
        ),
    ]
