# Generated by Django 4.2.15 on 2024-09-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_rename_order_homeprioritypage_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homeprioritypage",
            options={"ordering": ["sort_order"]},
        ),
    ]
