# Generated by Django 4.2.15 on 2024-09-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_homepage_priority_pages_layout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={
                "permissions": [
                    ("can_change_home_page_content", "Can change home page content")
                ],
                "verbose_name": "Home page",
            },
        ),
    ]
