# Generated by Django 4.2.15 on 2024-09-23 16:28

import core.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_homepage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatspopular",
            name="external_url",
            field=core.models.fields.URLField(blank=True, null=True),
        ),
    ]
