# Generated by Django 4.2.15 on 2024-09-25 15:44

import core.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0012_alter_whatspopular_external_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="promo_description",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Promotion banner description",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Enable promotion banner"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Promotion banner image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_link_text",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Promotion banner link text",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_link_url",
            field=core.models.fields.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_ribbon_text",
            field=models.CharField(
                blank=True,
                help_text="The text to be display on the ribbon. If empty, the ribbon will be hidden.",
                max_length=30,
                null=True,
                verbose_name="Promotion banner ribbon text",
            ),
        ),
    ]
