# Generated by Django 5.1.8 on 2025-04-25 11:10

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_homepage_promotion_banner_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="priority_pages_layout",
            field=core.field_models.CharField(
                choices=[
                    ("L1_0", "1 card"),
                    ("L2_0", "2 cards"),
                    ("L3_0", "3 cards"),
                    ("L1_2", "1 card then 2 cards"),
                    ("L1_3", "1 card then 3 cards"),
                    ("L2_3", "2 cards then 3 cards"),
                ],
                default="L1_3",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="promo_description",
            field=core.field_models.TextField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Promotion banner description",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="promo_link_text",
            field=core.field_models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Promotion banner link text",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="promo_ribbon_text",
            field=core.field_models.CharField(
                blank=True,
                help_text="The text to be display on the ribbon. If empty, the ribbon will be hidden.",
                max_length=30,
                null=True,
                verbose_name="Promotion banner ribbon text",
            ),
        ),
        migrations.AlterField(
            model_name="homeprioritypage",
            name="ribbon_text",
            field=core.field_models.CharField(
                blank=True,
                help_text="Insert a ribbon text for the news listing on the home page.",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quicklink",
            name="title",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="whatspopular",
            name="title",
            field=core.field_models.CharField(max_length=255),
        ),
    ]
