# Generated by Django 3.1.6 on 2021-02-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="peoplefinder.person",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="peoplefinder.team",
            ),
        ),
    ]
