# Generated by Django 3.1.6 on 2021-03-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('peoplefinder', '0003_person_pronouns'), ('peoplefinder', '0004_person_contact_email'), ('peoplefinder', '0005_auto_20210301_0858'), ('peoplefinder', '0006_person_country'), ('peoplefinder', '0007_person_town_city_or_region'), ('peoplefinder', '0008_auto_20210302_0840')]

    dependencies = [
        ('peoplefinder', '0002_auto_20210224_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pronouns',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='primary_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='town_city_or_region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='building',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ManyToManyField(to='peoplefinder.Country'),
        ),
    ]
