# Generated by Django 3.1.6 on 2021-03-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0003_person_pronouns_squashed_0008_auto_20210302_0840"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workday",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="international_building",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="location_in_building",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="regional_building",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name="person",
            name="country",
        ),
        migrations.AddField(
            model_name="person",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="peoplefinder.country",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="workdays",
            field=models.ManyToManyField(to="peoplefinder.Workday"),
        ),
    ]
