# Generated by Django 3.1.6 on 2021-03-02 09:58

from django.db import migrations


WORKDAYS = (
    ("mon", "Monday"),
    ("tue", "Tuesday"),
    ("wed", "Wednesday"),
    ("thu", "Thursday"),
    ("fri", "Friday"),
    ("sat", "Saturday"),
    ("sun", "Sunday"),
)


def insert_workday_data(apps, schema_editor):
    Workday = apps.get_model("peoplefinder", "Workday")

    Workday.objects.bulk_create(
        [Workday(code=code, name=name) for code, name in WORKDAYS]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0005_country_data"),
    ]

    operations = [migrations.RunPython(insert_workday_data)]
