# Generated by Django 3.1.6 on 2021-03-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0005_workday_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="country",
            field=models.ForeignKey(
                default="GB",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="peoplefinder.country",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="workdays",
            field=models.ManyToManyField(
                blank=True, null=True, to="peoplefinder.Workday"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="workdays",
            field=models.ManyToManyField(blank=True, to="peoplefinder.Workday"),
        ),
    ]
