# Generated by Django 3.1.6 on 2021-03-08 13:40

from django.db import migrations

GRADES = (
    ("fco_s1", "FCO S1"),
    ("fco_s2", "FCO S2"),
    ("fco_s3", "FCO S3"),
    ("admin_assistant", "Administrative assistant (AA)"),
    ("admin_officer", "Administrative officer (AO/A2)"),
    ("executive_officer", "Executive officer (EO/B3)"),
    ("higher_executive_officer", "Higher executive officer (HEO/C4)"),
    ("senior_executive_officer", "Senior executive officer (SEO/C5)"),
    ("grade_7", "Grade 7 (G7/D6)"),
    ("grade_6", "Grade 6 (G6/D7)"),
    ("scs_1", "Senior civil service 1 (SCS1/SMS1)"),
    ("scs_2", "Senior civil service 2 (SCS2/SMS2)"),
    ("scs_3", "Senior civil service 3 (SCS3/SMS3)"),
    ("scs_4", "Senior civil service 4 (SCS4/SMS4)"),
    ("fast_stream", "Fast Stream"),
    ("fast_track", "Fast Track"),
    ("apprentice", "Apprentice"),
    ("non_graded_special_advisor", "Non graded - special advisor (SPAD)"),
    ("non_graded_contractor", "Non graded - contractor"),
    ("non_graded_secondee", "Non graded - secondee"),
    ("non_graded_post", "Non graded - post"),
)


def insert_grade_data(apps, schema_editor):
    Grade = apps.get_model("peoplefinder", "Grade")

    Grade.objects.bulk_create([Grade(code=code, name=name) for code, name in GRADES])


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0007_auto_20210308_1344"),
    ]

    operations = [migrations.RunPython(insert_grade_data)]
