# Generated by Django 3.1.6 on 2021-03-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0008_auto_20210302_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='workdays',
            field=models.ManyToManyField(blank=True, to='peoplefinder.Workday'),
        ),
    ]
