# Generated by Django 3.1.8 on 2021-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0009_auto_20210520_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=""
            ),
        ),
    ]
