# Generated by Django 3.1.8 on 2021-06-09 08:16

from django.db import migrations

KEY_SKILLS = (
    ("asset_management", "Asset management"),
    ("assurance", "Assurance"),
    ("benefits_realisation", "Benefits realisation"),
    ("change_management", "Change management"),
    ("coaching", "Coaching"),
    ("commercial_specialist", "Commercial specialist"),
    ("commissioning", "Commissioning"),
    ("contract_management", "Contract management"),
    ("credit_risk_analysis", "Credit risk analysis"),
    ("customer_service", "Customer service"),
    ("digital", " Digital"),
    ("digital_workspace_publisher", "Digital Workspace publisher"),
    ("economist", "Economist"),
    ("financial_reporting", " Financial reporting"),
    ("graphic_design", "Graphic Design"),
    ("hr", "HR"),
    ("income_generation", "Income generation"),
    ("information_management", "Information management"),
    ("interviewing", "Interviewing"),
    ("it", "IT"),
    ("law", "Law"),
    ("lean", "Lean/ Six sigma"),
    ("line_management", "Line management"),
    ("media_trained", "Media trained"),
    ("mentoring", "Mentoring"),
    ("policy_design", "Policy design"),
    ("policy_implementation", "Policy implementation"),
    ("presenting", "Presenting"),
    ("project_delivery", "Project delivery"),
    ("project_management", "Project management"),
    ("property_estates", "Property / Estates"),
    ("research_operational", "Research - operational"),
    ("research_economic", "Research - economic"),
    ("research_statistical", "Research - statistical"),
    ("research_social", "Research - social"),
    ("risk_management", "Risk management"),
    ("security", "Security"),
    ("service_design", "Service and process design"),
    ("skills_and_capability", "Skills and capability management"),
    ("sponsorship", "Sponsorship and partnerships"),
    ("stakeholder_management", "Stakeholder management"),
    ("statistics", "Statistics"),
    ("strategy", "Strategy"),
    ("submission_writing", "Submission writing"),
    ("talent_management", "Talent Management"),
    ("tax", "Tax"),
    ("training", "Training"),
    ("underwriting", "Underwriting"),
    ("user_research", "User research"),
    ("valution", "Valuation"),
    ("working_with_devolved_admin", "Working with Devolved Administrations"),
    ("working_with_ministers", "Working with Ministers"),
    ("working_with_govt_depts", "Working with other government departments"),
)


def insert_key_skills_data(apps, schema_editor):
    KeySkill = apps.get_model("peoplefinder", "KeySkill")

    KeySkill.objects.bulk_create(
        [KeySkill(code=code, name=name) for code, name in KEY_SKILLS]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0012_auto_20210609_0858"),
    ]

    operations = [migrations.RunPython(insert_key_skills_data)]
