# Generated by Django 3.1.8 on 2021-06-10 10:24

from django.db import migrations


LEARNING_INTERESTS = (
    ("shadowing", "Work shadowing"),
    ("mentoring", "Mentoring"),
    ("research", "Research"),
    ("overseas_posts", "Overseas posts"),
    ("secondment", "Secondment"),
    ("parliamentary_work", "Parliamentary work"),
    ("ministerial_submissions", "Ministerial submissions"),
    ("coding", "Coding"),
)


def insert_learning_skills_data(apps, schema_editor):
    LearningInterest = apps.get_model("peoplefinder", "LearningInterest")

    LearningInterest.objects.bulk_create(
        [LearningInterest(code=code, name=name) for code, name in LEARNING_INTERESTS]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0016_auto_20210610_1016"),
    ]

    operations = [migrations.RunPython(insert_learning_skills_data)]
