# Generated by Django 3.1.8 on 2021-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0018_auto_20210610_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_network_code'),
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_network_name'),
        ),
        migrations.AddField(
            model_name='person',
            name='networks',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', related_name='_person_networks_+', to='peoplefinder.Network', verbose_name='What networks do you belong to?'),
        ),
    ]
