# Generated by Django 3.1.8 on 2021-06-10 11:23

from django.db import migrations


PROFESSIONS = (
    ("commercial", "Government commercial and contract management"),
    ("corp_finance", "Corporate finance profession"),
    ("counter_fraud", "Counter-fraud standards and profession"),
    ("digital_data_tech", "Digital, data and technology profession"),
    ("gov_comms", "Government communication service"),
    ("gov_economics", "Government economic service"),
    ("gov_finance", "Government finance profession"),
    ("gov_it", "Government IT profession"),
    ("gov_knowledge", "Government knowledge and information management profession"),
    ("gov_legal", "Government legal service"),
    ("gov_occupational", "Government occupational psychology profession"),
    ("gov_operational", "Government operational research service"),
    ("gov_planning_inspectors", "Government planning inspectors"),
    ("gov_planning_profession", "Government planning profession"),
    ("gov_property", "Government property profession"),
    ("gov_security", "Government security profession"),
    ("gov_science", "Government science and engineering profession"),
    ("gov_social", "Government social research profession"),
    ("gov_statistical", "Government statistical service profession"),
    ("gov_tax", "Government tax profession"),
    ("gov_vet", "Government veterinary profession"),
    ("human_resources", "Human resources profession"),
    ("intelligence_analysis", "Intelligence analysis"),
    ("internal_audit", "Internal audit profession"),
    ("medical_profession", "Medical profession"),
    ("operation_delivery", "Operational delivery profession"),
    ("policy_profiession", "Policy profession"),
    ("procurement_profession", "Procurement profession"),
    ("project_delivery", "Project delivery profession"),
    ("international_trade", "International trade profession"),
)


def insert_professions_data(apps, schema_editor):
    Profession = apps.get_model("peoplefinder", "Profession")

    Profession.objects.bulk_create(
        [Profession(code=code, name=name) for code, name in PROFESSIONS]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0021_auto_20210610_1123"),
    ]

    operations = [migrations.RunPython(insert_professions_data)]
