# Generated by Django 3.1.8 on 2021-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0024_additional_roles_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='previous_experience',
            field=models.TextField(blank=True, help_text='List where you have worked before your current role.', null=True, verbose_name='Previous positions I have held'),
        ),
    ]
