# Generated by Django 3.1.8 on 2021-06-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0025_person_previous_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
