# Generated by Django 3.1.12 on 2021-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0026_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='A short form of the team name, up to 10 characters. For example DDaT.', max_length=10, null=True, verbose_name='Team acronym or initials'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(default='Find out who is in the team and their contact details.\n\nYou can update this description, by [updating your team information](https://workspace.trade.gov.uk/working-at-dit/how-do-i/update-my-team-information-on-people-finder/).\n', help_text='What does this team do? Use Markdown to add lists and links. Enter up to 1500 characters.', verbose_name='Team description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='The full name of this team (e.g. Digital, Data and Technology)', max_length=255, unique=True, verbose_name='Team name (required)'),
        ),
    ]
