# Generated by Django 3.2.4 on 2021-08-18 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0030_auto_20210720_0959"),
    ]

    operations = [
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("ancestry", models.TextField(blank=True, null=True)),
                ("ancestry_depth", models.IntegerField()),
                ("acronym", models.TextField(blank=True, null=True)),
                (
                    "members_completion_score",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Memberships",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("leader", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "memberships",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("given_name", models.TextField(blank=True, null=True)),
                ("surname", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("primary_phone_number", models.TextField(blank=True, null=True)),
                ("secondary_phone_number", models.TextField(blank=True, null=True)),
                ("location_in_building", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("works_monday", models.BooleanField(blank=True, null=True)),
                ("works_tuesday", models.BooleanField(blank=True, null=True)),
                ("works_wednesday", models.BooleanField(blank=True, null=True)),
                ("works_thursday", models.BooleanField(blank=True, null=True)),
                ("works_friday", models.BooleanField(blank=True, null=True)),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("works_saturday", models.BooleanField(blank=True, null=True)),
                ("works_sunday", models.BooleanField(blank=True, null=True)),
                ("login_count", models.IntegerField()),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("role_administrator", models.BooleanField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("profile_photo_id", models.IntegerField(blank=True, null=True)),
                (
                    "building",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("skype_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "key_skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                ("language_fluent", models.TextField(blank=True, null=True)),
                ("language_intermediate", models.TextField(blank=True, null=True)),
                ("grade", models.TextField(blank=True, null=True)),
                ("previous_positions", models.TextField(blank=True, null=True)),
                (
                    "learning_and_development",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "networks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "additional_responsibilities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                ("other_uk", models.TextField(blank=True, null=True)),
                ("other_overseas", models.TextField(blank=True, null=True)),
                (
                    "other_key_skills",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_learning_and_development",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_additional_responsibilities",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "professions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "other_professions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ditsso_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pronouns", models.CharField(blank=True, max_length=255, null=True)),
                ("line_manager_id", models.IntegerField(blank=True, null=True)),
                (
                    "line_manager_not_required",
                    models.BooleanField(blank=True, null=True),
                ),
                ("role_people_editor", models.BooleanField(blank=True, null=True)),
                ("role_groups_editor", models.BooleanField(blank=True, null=True)),
                (
                    "last_edited_or_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "contact_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "people",
                "managed": False,
            },
        ),
    ]
