# Generated by Django 3.2.4 on 2021-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0032_alter_team_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='The full name of this team (e.g. Digital, Data and Technology)', max_length=255, verbose_name='Team name (required)'),
        ),
    ]
