# Generated by Django 3.2.4 on 2021-08-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0033_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(max_length=130),
        ),
    ]
