# Generated by Django 3.2.4 on 2021-08-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0034_alter_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
    ]
