# Generated by Django 3.2.4 on 2021-08-31 09:32

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0037_auto_20210825_0833'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(('pk', django.db.models.expressions.F('manager')), _negated=True), name='manager_cannot_be_self'),
        ),
    ]
