# Generated by Django 3.2.4 on 2021-09-01 11:38

from django.db import migrations


BUILDINGS = (
    ("home", "Remote (home worker)"),
    ("horse_guards", "1 Horse Guards Rd"),
    ("old_admiralty", "Old Admiralty Building"),
)


def insert_buildings_data(apps, schema_editor):
    Building = apps.get_model("peoplefinder", "Building")

    Building.objects.bulk_create(
        [Building(code=code, name=name) for code, name in BUILDINGS]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0039_auto_20210901_1137"),
    ]

    operations = [migrations.RunPython(insert_buildings_data)]
