# Generated by Django 3.2.4 on 2021-09-01 14:01

import uuid

from django.db import migrations


def generate_person_uuids(apps, schema_editor):
    Person = apps.get_model("peoplefinder", "Person")

    for row in Person.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0041_person_uuid"),
    ]

    operations = [migrations.RunPython(generate_person_uuids)]
