# Generated by Django 3.2.4 on 2021-09-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0044_person_legacy_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='uuid',
            new_name='slug',
        ),
    ]
