# Generated by Django 3.2.4 on 2021-09-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0041_alter_team_slug'),
        ('peoplefinder', '0045_rename_uuid_person_slug'),
    ]

    operations = [
    ]
