# Generated by Django 3.2.4 on 2021-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0046_merge_20210902_1355'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('person', 'team', 'job_title', 'head_of_team'), name='unique_team_member'),
        ),
    ]
