# Generated by Django 3.2.4 on 2021-09-06 10:23

from django.db import migrations


def copy_name_and_email(apps, schema_editor):
    Person = apps.get_model("peoplefinder", "Person")

    for person in Person.objects.all():
        person.first_name = person.user.first_name
        person.last_name = person.user.last_name
        person.email = person.user.email
        person.save(update_fields=["first_name", "last_name", "email"])


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0050_auto_20210906_1022"),
    ]

    operations = [migrations.RunPython(copy_name_and_email)]
