# Generated by Django 3.2.10 on 2022-02-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0056_create_people_finder_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('edit_profile', 'Edit profile'), ('delete_profile', 'Delete profile'))},
        ),
    ]
