# Generated by Django 3.2.11 on 2022-03-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0058_alter_auditlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="login_count",
            field=models.IntegerField(default=0),
        ),
    ]
