# Generated by Django 3.2.12 on 2022-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplefinder', '0059_auto_20220304_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='became_inactive',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
