# Generated by Django 3.2.12 on 2022-03-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0061_legacyauditlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legacyauditlog",
            options={"ordering": ["timestamp"]},
        ),
    ]
