# Generated by Django 3.2.12 on 2022-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0063_merge_20220309_1137"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="became_inactive",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
