# Generated by Django 3.2.12 on 2022-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0064_auto_20220315_1159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="secondary_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter an alternative contact telephone number. Include your country dialling code.",
                max_length=160,
                null=True,
                verbose_name="Alternative contact number",
            ),
        ),
    ]
