# Generated by Django 3.2.12 on 2022-03-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0066_legacyauditlog_automated"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="id",
            field=models.IntegerField(null=True),
        ),
    ]
