# Generated by Django 3.2.12 on 2022-03-17 13:38

from django.db import migrations


def insert_person_id(apps, schema_editor):
    Person = apps.get_model("peoplefinder", "Person")

    for i, person in enumerate(Person.objects.all()):
        person.id = i + 1
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0067_person_id"),
    ]

    operations = [migrations.RunPython(insert_person_id)]
