# Generated by Django 3.2.12 on 2022-03-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0071_auto_20220317_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="peoplefinder.person",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="people",
            field=models.ManyToManyField(
                related_name="teams",
                through="peoplefinder.TeamMember",
                to="peoplefinder.Person",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="peoplefinder.person",
            ),
        ),
        migrations.DeleteModel(
            name="OldPerson",
        ),
    ]
