# Generated by Django 3.2.12 on 2022-03-17 14:03

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0072_auto_20220317_1402"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="person",
            name="new_manager_cannot_be_self",
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("pk", django.db.models.expressions.F("manager")), _negated=True
                ),
                name="manager_cannot_be_self",
            ),
        ),
    ]
