# Generated by Django 3.2.12 on 2022-03-18 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0074_alter_person_user"),
    ]

    operations = []
