# Generated by Django 3.2.12 on 2022-03-18 10:51

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0074_alter_person_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="person",
            name="manager_cannot_be_self",
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user", django.db.models.expressions.F("manager")), _negated=True
                ),
                name="manager_cannot_be_self",
            ),
        ),
    ]
