# Generated by Django 3.2.12 on 2022-03-18 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0064_auto_20220315_1622"),
        ("peoplefinder", "0075_auto_20220318_1051"),
    ]

    operations = []
