# Generated by Django 3.2.12 on 2022-03-30 12:36

from django.db import migrations


def insert_edited_or_confirmed_at(apps, schema_editor):
    Person = apps.get_model("peoplefinder", "Person")

    for person in Person.objects.all():
        person.edited_or_confirmed_at = person.updated_at
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0077_person_edited_or_confirmed_at"),
    ]

    operations = [migrations.RunPython(insert_edited_or_confirmed_at)]
