# Generated by Django 3.2.12 on 2022-03-30 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0079_alter_person_edited_or_confirmed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="edited_or_confirmed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
