# Generated by Django 3.2.12 on 2022-04-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0059_person_login_count"),
        ("peoplefinder", "0080_alter_person_edited_or_confirmed_at"),
    ]

    operations = []
