# Generated by Django 3.2.12 on 2022-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0081_merge_20220407_0836"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="leaders_ordering",
            field=models.CharField(
                choices=[("alphabetical", "Alphabetical"), ("custom", "Custom")],
                default="alphabetical",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="leaders_position",
            field=models.SmallIntegerField(null=True),
        ),
    ]
