# Generated by Django 3.2.13 on 2022-04-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0082_auto_20220419_1049"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="person",
            name="manager_cannot_be_self",
        ),
    ]
