# Generated by Django 3.2.13 on 2022-04-28 16:08

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0083_remove_person_manager_cannot_be_self"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("pk", django.db.models.expressions.F("manager")), _negated=True
                ),
                name="manager_cannot_be_self",
            ),
        ),
    ]
