# Generated by Django 3.2.13 on 2022-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0085_auto_20220509_1140"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="legacy_sso_user_id",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
