# Generated by Django 3.2.13 on 2022-05-18 15:06

from django.db import migrations


def fix_key_skill_names(apps, schema_editor):
    KeySkill = apps.get_model("peoplefinder", "KeySkill")

    digital = KeySkill.objects.get(code="digital")
    digital.name = "Digital"
    digital.save()

    financial_reporting = KeySkill.objects.get(code="financial_reporting")
    financial_reporting.name = "Financial reporting"
    financial_reporting.save()


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0086_person_legacy_sso_user_id"),
    ]

    operations = [migrations.RunPython(fix_key_skill_names)]
