# Generated by Django 3.2.13 on 2022-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0087_fix_key_skill_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="leaders_ordering",
            field=models.CharField(
                blank=True,
                choices=[("alphabetical", "Alphabetical"), ("custom", "Custom")],
                default="alphabetical",
                max_length=12,
            ),
        ),
    ]
