# Generated by Django 3.2.13 on 2022-05-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0004_country_type"),
        ("peoplefinder", "0088_alter_team_leaders_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="new_country",
            field=models.ForeignKey(
                default="CTHMTC00260",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="countries.country",
            ),
        ),
    ]
