# Generated by Django 3.2.13 on 2022-05-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0090_data_person_new_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person", old_name="country", new_name="old_country"
        ),
        migrations.RenameField(
            model_name="person", old_name="new_country", new_name="country"
        ),
    ]
