# Generated by Django 3.2.13 on 2022-06-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0091_switch_person_country_columns"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Groups",
        ),
        migrations.DeleteModel(
            name="Memberships",
        ),
        migrations.DeleteModel(
            name="People",
        ),
        migrations.DeleteModel(
            name="ProfilePhotos",
        ),
        migrations.DeleteModel(
            name="Versions",
        ),
    ]
