# Generated by Django 3.2.13 on 2022-06-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0002_network_excerpt"),
        ("peoplefinder", "0092_auto_20220621_1030"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewNetwork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="networks.network",
                    ),
                ),
            ],
        ),
    ]
