# Generated by Django 3.2.13 on 2022-06-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0002_network_excerpt"),
        ("peoplefinder", "0093_newnetwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newnetwork",
            name="page",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="networks.network"
            ),
        ),
    ]
