# Generated by Django 3.2.13 on 2022-06-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0095_newnetwork_old_network"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newnetwork",
            name="old_network",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peoplefinder.network",
            ),
        ),
    ]
