# Generated by Django 3.2.14 on 2022-07-25 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0096_alter_newnetwork_old_network"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="old_country",
        ),
    ]
