# Generated by Django 3.2.14 on 2022-07-25 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0097_remove_person_old_country"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Country",
        ),
    ]
