# Generated by Django 3.2.18 on 2023-03-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0098_delete_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="do_not_work_for_dit",
            field=models.BooleanField(
                default=False,
                verbose_name="My manager is not listed because I do not work for DBT",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(
                default="Find out who is in the team and their contact details.\n\nYou can update this description, by [updating your team information](https://workspace.trade.gov.uk/working-at-dbt/how-do-i/update-my-team-information-on-people-finder/).\n",
                help_text="What does this team do? Use Markdown to add lists and links. Enter up to 1500 characters.",
                verbose_name="Team description",
            ),
        ),
    ]
