# Generated by Django 4.1 on 2023-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0098_delete_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="additional_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select all that apply",
                related_name="+",
                to="peoplefinder.additionalrole",
                verbose_name="Do you have any additional roles or responsibilities?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="buildings",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="peoplefinder.building",
                verbose_name="Where do you usually work?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="key_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select all that apply",
                related_name="+",
                to="peoplefinder.keyskill",
                verbose_name="What are your skills?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="learning_interests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select all that apply",
                related_name="+",
                to="peoplefinder.learninginterest",
                verbose_name="What are your learning and development interests?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="networks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select all that apply",
                related_name="+",
                to="peoplefinder.network",
                verbose_name="What networks do you belong to?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="professions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select all that apply",
                related_name="+",
                to="peoplefinder.profession",
                verbose_name="What professions do you belong to?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="workdays",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="peoplefinder.workday",
                verbose_name="Which days do you usually work?",
            ),
        ),
    ]
