# Generated by Django 3.2.18 on 2023-03-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0099_auto_20230302_0923"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
