# Generated by Django 4.1 on 2023-04-19 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "peoplefinder",
            "0099_alter_person_additional_roles_alter_person_buildings_and_more",
        ),
        ("peoplefinder", "0100_alter_team_slug"),
    ]

    operations = []
