# Generated by Django 4.1 on 2023-04-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "peoplefinder",
            "0101_alter_person_additional_roles_alter_person_buildings_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="person",
            name="manager_cannot_be_self",
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                check=models.Q(("id", models.F("manager")), _negated=True),
                name="manager_cannot_be_self",
            ),
        ),
    ]
