# Generated by Django 3.2.13 on 2022-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0003_auto_20220107_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="type",
            field=models.CharField(
                choices=[("country", "Country"), ("territory", "Territory")],
                default="country",
                max_length=9,
            ),
            preserve_default=False,
        ),
    ]
