# Generated by Django 3.0.7 on 2020-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="redirect_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
