# Generated by Django 4.1.7 on 2023-06-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0003_auto_20201029_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="long_description",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
