# Generated by Django 4.1.7 on 2023-06-15 16:53

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0003_auto_20201029_1218"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrapToolData",
            fields=[
                (
                    "product_irap_reference_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "functionality",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "after_import_status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("unchanged", "Unchanged"),
                            ("changed", "Changed"),
                            ("deleted", "Deleted"),
                        ],
                        default="new",
                        max_length=9,
                    ),
                ),
                ("reviewed", models.BooleanField(default=False)),
                ("reviewed_date", models.DateTimeField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IrapToolDataImport",
            fields=[
                (
                    "product_irap_reference_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "functionality",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tool",
            name="long_description",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="irap_tool",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tools.iraptooldata",
            ),
        ),
    ]
