# Generated by Django 4.2.15 on 2024-09-23 16:28

import core.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0004_iraptooldata_iraptooldataimport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="redirect_url",
            field=core.models.fields.URLField(blank=True, null=True),
        ),
    ]
