# Generated by Django 4.1.7 on 2023-06-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0004_tool_long_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrapData",
            fields=[
                (
                    "product_irap_reference_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "functionality",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "latest_accreditation_status",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tool",
            name="functionality",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="latest_accreditation_status",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="product_irap_reference_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="product_name",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
