# Generated by Django 5.1.8 on 2025-04-25 11:07

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0005_tool_new_redirect_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iraptooldata",
            name="after_import_status",
            field=core.field_models.CharField(
                choices=[
                    ("new", "new"),
                    ("changed", "Changed"),
                    ("deleted", "Deleted"),
                    ("undeleted", "Undeleted"),
                    ("reviewed", "Reviewed"),
                ],
                default="new",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="iraptooldata",
            name="functionality",
            field=core.field_models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="iraptooldata",
            name="product_name",
            field=core.field_models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="iraptooldataimport",
            name="functionality",
            field=core.field_models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="iraptooldataimport",
            name="product_name",
            field=core.field_models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="long_description",
            field=core.field_models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
