# Generated by Django 4.1.7 on 2023-06-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0005_irapdata_tool_functionality_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrapToolData",
            fields=[
                (
                    "product_irap_reference_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "functionality",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IrapToolDataImport",
            fields=[
                (
                    "product_irap_reference_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "functionality",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="IrapData",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="functionality",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="latest_accreditation_status",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="product_irap_reference_number",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="product_name",
        ),
        migrations.AddField(
            model_name="tool",
            name="irap_tool",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tools.iraptooldata",
            ),
        ),
    ]
