# Generated by Django 4.1.9 on 2023-06-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0003_auto_20230209_1441"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("change_boost", "Edit boost settings for search components"),
                    ("view_explore", "View the global search explore page"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
