# Generated by Django 4.1.9 on 2023-07-18 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0004_searchsettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchSettings",
        ),
    ]
