# Generated by Django 5.1.8 on 2025-04-25 11:10

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_delete_searchsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excludefromsearch",
            name="term",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalexcludefromsearch",
            name="term",
            field=core.field_models.CharField(max_length=255),
        ),
    ]
