from wagtail import blocks

def get_tag_choices():
    return [(tag.name, tag.name) for tag in Tags.objects.all()]

class TaggedPageListBlock(blocks.StructBlock):
    title = blocks.CharBlock(
        label="Title",
        icon="title",
        classname="full title",
        max_length=40,
        search_index=False,
    )
    description = blocks.CharBlock(required=False, max_length=40)
    tag = blocks.ChoiceBlock(Tags.objects.all())

    class Meta:
       template = "dwds/components/link_list.html"
       label = "Link list"
       help_text = "Autogenerated list of links based on selected tag"

class CustomPageLinkListBlock(blocks.StructBlock):
    class Meta:
        template = "dwds/components/link_list.html"
        label = "Link list"
        help_text = "List of links to specific pages"

    title = blocks.CharBlock(
        label="Title",
        icon="title",
        classname="full title",
        max_length=40,
        search_index=False,
    )
    description = blocks.CharBlock(required=False, max_length=40)
    pages = blocks.ListBlock(blocks.PageChooserBlock(label="Page"), search_index=False)

    def get_context(self, value, parent_context=None):
        context = parent_context or {}
        context.update(
            title=value["title"],
            description=value["description"],
            list=[
                {"url": page.get_url(), "text": page.title} for page in value["pages"]
            ],
        )
        return context
