# Generated by Django 3.2.10 on 2022-01-10 13:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_historicalcomment_historicalnewscategory'),
        ('home', '0003_quicklink_result_weighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeNewsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('news_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_news_order_pages', to='news.newspage')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
