# Generated by Django 3.2.10 on 2022-01-10 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_homenewsorder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homenewsorder",
            options={
                "ordering": ["order"],
                "verbose_name": "Home page news order",
                "verbose_name_plural": "Home page news order",
            },
        ),
    ]
