# Generated by Django 4.2.14 on 2024-08-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0042_alter_basepage_options"),
        ("peoplefinder", "0121_merge_20240430_0948"),
    ]

    operations = []
