# Generated by Django 4.2.14 on 2024-08-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventsHome",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.basepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.basepage",),
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentpage",
                    ),
                ),
                ("event_date", models.DateTimeField()),
                ("event_url", models.URLField(blank=True, null=True)),
                ("submit_questions_url", models.URLField(blank=True, null=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "All staff"),
                            ("grade_7", "Grade 7 (G7/D6)"),
                            ("grade_6", "Grade 6 (G6/D7)"),
                            ("scs_1", "Senior civil service 1 (SCS1/SMS1)"),
                            ("scs_2", "Senior civil service 2 (SCS2/SMS2)"),
                        ],
                        default="all",
                    ),
                ),
                ("room", models.CharField(blank=True, null=True)),
                (
                    "in_person_only",
                    models.BooleanField(
                        default=False,
                        help_text="Tick this box if this event is being held in person only.",
                        verbose_name="In person only event?",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="peoplefinder.ukstafflocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.contentpage",),
        ),
    ]
