# Generated by Django 4.2.15 on 2024-09-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0121_merge_20240430_0948"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="If you don't select a location the page will show 'Location: To be confirmed'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peoplefinder.ukstafflocation",
            ),
        ),
    ]
