# Generated by Django 4.2.15 on 2024-08-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="in_person_only",
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("in_person", "In person"),
                    ("online", "Online"),
                    ("hybrid", "Hybrid"),
                ],
                default="online",
            ),
        ),
    ]
