# Generated by Django 4.2.15 on 2024-08-21 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="end_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2024, 8, 21, 14, 36, 16, 742931, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventpage",
            name="start_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2024, 8, 21, 14, 36, 29, 802570, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="event_date",
            field=models.DateField(),
        ),
    ]
