# Generated by Django 4.2.15 on 2024-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="event_url",
            field=models.URLField(
                blank=True,
                help_text="If the event is online, you can add a link here for others to join.",
                null=True,
                verbose_name="Online event url",
            ),
        ),
    ]
