# Generated by Django 4.2.15 on 2024-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_eventpage_in_person_only_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="event_url",
        ),
        migrations.AddField(
            model_name="eventpage",
            name="offline_event_url",
            field=models.URLField(
                blank=True,
                help_text="If the event is offline, you can add a link here for registration.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="online_event_url",
            field=models.URLField(
                blank=True,
                help_text="If the event is online, you can add a link here for others to join.",
                null=True,
            ),
        ),
    ]
