# Generated by Django 4.2.15 on 2024-08-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventpage_end_time_eventpage_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="submit_questions_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a page for others to submit their questions.",
                null=True,
            ),
        ),
    ]
