# Generated by Django 4.2.15 on 2024-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_eventpage_description_alter_eventpage_event_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="room_capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
