# Generated by Django 4.2.15 on 2024-08-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventpage_room_capacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="description",
        ),
    ]
