# Generated by Django 5.1.8 on 2025-04-25 11:07

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_eventpage_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="audience",
            field=core.field_models.CharField(
                blank=True,
                choices=[
                    ("all", "All staff"),
                    ("grade_7", "Grade 7 (G7/D6)"),
                    ("grade_6", "Grade 6 (G6/D7)"),
                    ("scs_1", "Senior civil service 1 (SCS1/SMS1)"),
                    ("scs_2", "Senior civil service 2 (SCS2/SMS2)"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="event_type",
            field=core.field_models.CharField(
                choices=[
                    ("in_person", "In person"),
                    ("online", "Online"),
                    ("hybrid", "Hybrid"),
                ],
                default="online",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="room",
            field=core.field_models.CharField(blank=True, null=True),
        ),
    ]
