# Generated by Django 4.2.11 on 2024-04-03 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0010_remove_historicaluser_enable_v2_search_and_more"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.page",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntranetProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="intranet",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bookmarks",
                    models.ManyToManyField(
                        related_name="+",
                        through="intranet_profile.Bookmark",
                        to="wagtailcore.page",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecentPageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="intranet_profile.intranetprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_viewed_at"],
            },
        ),
        migrations.AddField(
            model_name="intranetprofile",
            name="recent_page_views",
            field=models.ManyToManyField(
                related_name="+",
                through="intranet_profile.RecentPageView",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="intranet_profile.intranetprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="recentpageview",
            constraint=models.UniqueConstraint(
                fields=("profile", "page"), name="unique_recent_page_view"
            ),
        ),
    ]
