# Generated by Django 3.0.7 on 2020-11-27 05:14

from django.db import migrations, models

# import s3chunkuploader.fields


class Migration(migrations.Migration):

    dependencies = [
        ("country_fact_sheet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countryfactsheetupload",
            name="file_name",
        ),
        migrations.AddField(
            model_name="countryfactsheetupload",
            name="s3_document_file",
            field=models.FileField(
                blank=True, max_length=1000, null=True, upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="countryfactsheetupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("unprocessed", "Unprocessed"),
                    ("antivirus", "Checking for viruses"),
                    ("processed_error", "Processed. Page not created, error(s) found."),
                    ("Found virus", "Processed. Found virus."),
                    ("processing", "Processing"),
                    ("processed", "Processed and page created"),
                ],
                default="unprocessed",
                max_length=100,
            ),
        ),
    ]
