# Generated by Django 3.0.7 on 2020-11-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_fact_sheet", "0002_auto_20201127_0514"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryfactsheetupload",
            name="error_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="countryfactsheetupload",
            name="user_error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
