# Generated by Django 4.1.10 on 2023-08-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_feedback_govuk", "0004_alter_basefeedback_id"),
        ("feedback", "0002_migrate_search_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchFeedbackV2",
            fields=[
                (
                    "basefeedback_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_feedback_govuk.basefeedback",
                    ),
                ),
                ("search_query", models.CharField(max_length=255)),
                ("useful", models.BooleanField(default=True)),
                ("not_useful_comment", models.TextField(blank=True)),
                ("trying_to_find", models.TextField(blank=True)),
                ("search_data", models.JSONField(blank=True, default=dict, null=True)),
            ],
            bases=("django_feedback_govuk.basefeedback",),
        ),
    ]
