# Generated by Django 4.2.11 on 2024-05-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_feedback_govuk", "0004_alter_basefeedback_id"),
        ("feedback", "0003_searchfeedbackv2"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRFeedback",
            fields=[
                (
                    "basefeedback_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_feedback_govuk.basefeedback",
                    ),
                ),
                ("page_url", models.CharField(blank=True)),
                ("useful", models.BooleanField(default=True)),
                ("contactable", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True)),
            ],
            bases=("django_feedback_govuk.basefeedback",),
        ),
    ]
