# Generated by Django 4.2.15 on 2024-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_alter_hrfeedback_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrfeedback",
            name="page_url",
            field=models.CharField(blank=True),
        ),
    ]
