# Generated by Django 5.1.8 on 2025-04-25 11:07

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_alter_hrfeedback_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrfeedback",
            name="comment",
            field=core.field_models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="hrfeedback",
            name="page_url",
            field=core.field_models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="searchfeedbackv1",
            name="comment",
            field=core.field_models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="searchfeedbackv1",
            name="satisfaction",
            field=core.field_models.CharField(
                choices=[
                    ("very_dissatisfied", "Very dissatisfied"),
                    ("dissatisfied", "Dissatisfied"),
                    ("neutral", "Neither satisfied or dissatisfied"),
                    ("satisfied", "Satisfied"),
                    ("very_satisfied", "Very satisfied"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="searchfeedbackv2",
            name="not_useful_comment",
            field=core.field_models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="searchfeedbackv2",
            name="search_query",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="searchfeedbackv2",
            name="trying_to_find",
            field=core.field_models.TextField(blank=True),
        ),
    ]
