# Generated by Django 3.0.7 on 2020-08-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('working_at_dit', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='working_at_dit.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('working_at_dit.pagewithtopics',),
        ),
        migrations.CreateModel(
            name='PoliciesAndGuidance',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='working_at_dit.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('working_at_dit.pagewithtopics',),
        ),
    ]
