# Generated by Django 5.1.6 on 2025-03-05 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0004_reaction"),
        ("news", "0018_newspage_allow_reactions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("celebrate", "Celebrate"),
                            ("like", "Like"),
                            ("love", "Love"),
                            ("dislike", "Dislike"),
                            ("unhappy", "Unhappy"),
                        ],
                        help_text="Select the type of reaction (e.g., Like or Dislike).",
                        max_length=10,
                        verbose_name="Reaction Type",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="news.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "comment"),
                        name="unique_interactions_commentreaction",
                    )
                ],
            },
        ),
    ]
