# Generated by Django 5.1.5 on 2025-02-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0004_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("celebrate", "Celebrate"),
                    ("like", "Like"),
                    ("love", "Love"),
                    ("dislike", "Dislike"),
                ],
                help_text="Select the type of reaction (e.g., Like or Dislike).",
                max_length=10,
                verbose_name="Reaction Type",
            ),
        ),
    ]
