# Generated by Django 5.1.6 on 2025-03-05 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0005_commentreaction"),
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reaction",
            new_name="PageReaction",
        ),
        migrations.RemoveConstraint(
            model_name="pagereaction",
            name="unique_interactions_reaction",
        ),
        migrations.AddConstraint(
            model_name="pagereaction",
            constraint=models.UniqueConstraint(
                fields=("user", "page"), name="unique_interactions_pagereaction"
            ),
        ),
    ]
