# Generated by Django 5.1.8 on 2025-04-25 11:10

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0006_rename_reaction_pagereaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreaction",
            name="type",
            field=core.field_models.CharField(
                choices=[
                    ("celebrate", "Celebrate"),
                    ("like", "Like"),
                    ("love", "Love"),
                    ("dislike", "Dislike"),
                    ("unhappy", "Unhappy"),
                ],
                help_text="Select the type of reaction (e.g., Like or Dislike).",
                max_length=10,
                verbose_name="Reaction Type",
            ),
        ),
        migrations.AlterField(
            model_name="pagereaction",
            name="type",
            field=core.field_models.CharField(
                choices=[
                    ("celebrate", "Celebrate"),
                    ("like", "Like"),
                    ("love", "Love"),
                    ("dislike", "Dislike"),
                    ("unhappy", "Unhappy"),
                ],
                help_text="Select the type of reaction (e.g., Like or Dislike).",
                max_length=10,
                verbose_name="Reaction Type",
            ),
        ),
    ]
