# Generated by Django 4.2.11 on 2024-05-20 11:04

from django.db import migrations, models
import django.db.models.deletion
import extended_search.index
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0032_alter_navigationpage_secondary_elements"),
        ("core", "0005_fix_waffle_truncate_issue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(extended_search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="TaggedPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="content.contentpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("tag", "content_object")},
            },
        ),
    ]
