# Generated by Django 4.2.11 on 2024-03-14 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_fix_waffle_truncate_issue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsitealertbanner",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="SiteAlertBanner",
        ),
        migrations.DeleteModel(
            name="HistoricalSiteAlertBanner",
        ),
    ]
