# Generated by Django 4.2.17 on 2024-12-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_tag_taggedpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaldocument",
            name="file_size",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
