# Generated by Django 5.1.7 on 2025-03-24 11:13

from django.db import migrations, models


def create_initial_external_link_settings(apps, schema_editor):
    """
    Create initial ExternalLinkSetting objects for the default domains.
    """
    ExternalLinkSetting = apps.get_model("core", "ExternalLinkSetting")

    # List of domains to exclude from external link text functionality
    exclude_domains = [
        "localhost",
    ]
    # List of default domains and their corresponding external link text
    default_domains = [
        ("gov.uk", "GOV UK"),
        ("www.gov.uk", "GOV UK"),
    ]

    for domain in exclude_domains:
        ExternalLinkSetting.objects.create(domain=domain, exclude=True)

    for domain, text in default_domains:
        ExternalLinkSetting.objects.create(domain=domain, external_link_text=text)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_historicaldocument_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalLinkSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="The domain to match for this setting (example: gov.uk).",
                        max_length=255,
                    ),
                ),
                (
                    "exclude",
                    models.BooleanField(
                        default=False,
                        help_text="Don't show the external link text for this domain.",
                    ),
                ),
                (
                    "external_link_text",
                    models.CharField(
                        blank=True,
                        help_text="The text to show for this domain (example: GOV UK).",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "unique_together": {("domain", "exclude")},
            },
        ),
        migrations.RunPython(
            create_initial_external_link_settings,
            migrations.RunPython.noop,
        ),
    ]
