# Generated by Django 5.1.8 on 2025-04-17 10:32

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_externallinksetting"),
        ("peoplefinder", "0124_update_profile_completion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "tag_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.tag",),
        ),
        migrations.CreateModel(
            name="TaggedPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_people",
                        to="peoplefinder.person",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("tag", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="TaggedTeam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_teams",
                        to="peoplefinder.team",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("tag", "content_object")},
            },
        ),
    ]
