# Generated by Django 5.1.8 on 2025-04-23 17:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_externallinksetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageProblemFormSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", wagtail.fields.RichTextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
