# Generated by Django 5.1.8 on 2025-04-25 11:10

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_pageproblemformsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallinksetting",
            name="domain",
            field=core.field_models.CharField(
                help_text="The domain to match for this setting (example: gov.uk).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="externallinksetting",
            name="external_link_text",
            field=core.field_models.CharField(
                blank=True,
                help_text="The text to show for this domain (example: GOV UK).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsitealertbanner",
            name="banner_link",
            field=core.field_models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsitealertbanner",
            name="banner_text",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sitealertbanner",
            name="banner_link",
            field=core.field_models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sitealertbanner",
            name="banner_text",
            field=core.field_models.CharField(max_length=255),
        ),
    ]
