# Generated by Django 5.1.8 on 2025-04-17 10:32

from django.db import migrations

def create_simplify_campaign_tag(apps, schema_editor):
    Campaign = apps.get_model("core", "Campaign")
    Campaign.objects.get_or_create(
        name="Simplify",
        slug="simplify",
    )

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_campaign_taggedperson_taggedteam"),
    ]

    operations = [
        migrations.RunPython(
            code=create_simplify_campaign_tag,
            reverse_code=migrations.RunPython.noop,
        )
    ]
