# Generated by Django 5.1.8 on 2025-04-17 15:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_simplify_campaign_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taggedpage",
            name="tag",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.tag",
            ),
        ),
        migrations.AlterField(
            model_name="taggedperson",
            name="tag",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.tag",
            ),
        ),
        migrations.AlterField(
            model_name="taggedteam",
            name="tag",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.tag",
            ),
        ),
    ]
