# Generated by Django 5.1.9 on 2025-05-19 15:16

import core.models.tags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0010_campaign_alter_taggedpage_tag_taggedperson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="content_type",
            field=models.ForeignKey(
                default=core.models.tags.get_default_tag_content_type_id,
                on_delete=models.SET(core.models.tags.get_default_tag_content_type),
                related_name="tags",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
    ]
