# Generated by Django 5.1.9 on 2025-05-19 18:41

import core.models.tags
from django.db import migrations, models


def update_tag_content_types(apps, schema_editor):
    Campaign = apps.get_model("core", "Campaign")
    ContentType = apps.get_model("contenttypes", "ContentType")
    campaign_content_type = ContentType.objects.get_for_model(Campaign)

    for campaign_tag in Campaign.objects.all():
        campaign_tag.content_type = campaign_content_type
        campaign_tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0011_tag_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="content_type",
            field=models.ForeignKey(
                on_delete=models.SET(core.models.tags.get_default_tag_content_type),
                related_name="tags",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.RunPython(
            update_tag_content_types,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
