# Generated by Django 3.0.7 on 2020-08-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_auto_20200813_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='TransitionHome',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
    ]
