NEW_GTM_DATALAYER = "new_gtm_datalayer"
NETWORK_TYPES = "network_types"
NETWORKS_HUB = "networks_hub"
SHARE_TEAMS = "share_teams"
NEW_COMMENTS = "new_comments"
NEW_NEWS_AUTHOR = "new_news_author"
EXTERNAL_LINKS = "external_links"
PF_DISCOVER = "pf_discover"
