# Generated by Django 3.0.7 on 2020-10-29 09:07

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.ContentPage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.contentpage",),
        ),
        migrations.CreateModel(
            name="NetworksHome",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.ContentPage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.contentpage",),
        ),
    ]
