# Generated by Django 3.0.7 on 2020-11-13 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("working_at_dit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topictheme",
            options={"ordering": ["topic__title"]},
        ),
    ]
