# Generated by Django 4.1.9 on 2023-06-07 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("working_at_dit", "0005_rebrand_to_dbt"),
        ("content", "0018_remove_contentpage_body_no_html_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE content_contentpage AS cp SET search_excerpt = (SELECT excerpt FROM working_at_dit_pagewithtopics AS wadpwt WHERE wadpwt.contentpage_ptr_id = cp.basepage_ptr_id);",
            reverse_sql="UPDATE working_at_dit_pagewithtopics AS wadpwt SET excerpt = (SELECT search_excerpt FROM content_contentpage AS cp WHERE wadpwt.contentpage_ptr_id = cp.basepage_ptr_id);"
        ),
        migrations.RemoveField(
            model_name="pagewithtopics",
            name="excerpt",
        ),
    ]
