# Generated by Django 4.2.11 on 2024-04-18 15:02

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0026_alter_contentpage_body"),
        ("working_at_dit", "0007_guidance_content_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagetopic",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_topics",
                to="content.contentpage",
            ),
        ),
    ]
