# Generated by Django 4.2.11 on 2024-05-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("working_at_dit", "0008_alter_pagetopic_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagetopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_pages",
                to="working_at_dit.topic",
            ),
        ),
    ]
