# Generated by Django 3.1.8 on 2021-05-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0008_grade_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="location_in_building",
        ),
        migrations.AlterField(
            model_name="person",
            name="building",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Where do you usually work?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Enter the email address your colleagues should contact you on, for example, a jobshare or Private Office mailbox. This will be shown on your profile instead of your main work email address. Do not enter a personal email address, or a work email address that is not safe for official information.",
                max_length=254,
                null=True,
                verbose_name="Contact email address",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="do_not_work_for_dit",
            field=models.BooleanField(
                default=False,
                verbose_name="My manager is not listed because I do not work for DIT",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="international_building",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="International building or location",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="primary_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter your preferred contact telephone number. Include your country dialling code.",
                max_length=20,
                null=True,
                verbose_name="Preferred contact number",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="regional_building",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="UK regional building or location",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="secondary_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter an alternative contact telephone number. Include your country dialling code.",
                max_length=20,
                null=True,
                verbose_name="Alternative contact number",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="town_city_or_region",
            field=models.CharField(
                blank=True,
                help_text="For example, London",
                max_length=50,
                null=True,
                verbose_name="Town, city or region",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="workdays",
            field=models.ManyToManyField(
                blank=True,
                related_name="_person_workdays_+",
                to="peoplefinder.Workday",
                verbose_name="Which days do you usually work?",
            ),
        ),
    ]
