# Generated by Django 3.1.8 on 2021-06-10 10:44

from django.db import migrations


NETWORKS = (
    ("generation", "Generation network"),
    ("bame", "Black, Asian and Minority Ethnic (BAME) network"),
    ("celtic", "Celtic network"),
    ("coffee", "Trade coffee network"),
    ("disability", "Disability network"),
    ("eu_nationals", "EU nationals group"),
    ("lgbt_plus", "LGBTQ+ network"),
    ("parents", "Parents group"),
    ("faith_group", "Faith group"),
    ("gender", "Gender network"),
    ("muslim_women", "Muslim women's network"),
    ("mentoring", "Mentoring network"),
    ("social_mobility", "Social mobility network"),
    ("neurodiversity", "Neurodiversity network"),
    ("overseas", "Overseas network"),
)


def insert_networks_data(apps, schema_editor):
    Network = apps.get_model("peoplefinder", "Network")

    Network.objects.bulk_create(
        [Network(code=code, name=name) for code, name in NETWORKS]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0019_auto_20210610_1042"),
    ]

    operations = [migrations.RunPython(insert_networks_data)]
