# Generated by Django 3.1.8 on 2021-06-10 12:47

from django.db import migrations


ADDITIONAL_ROLES = (
    ("fire_warden", "Fire warden"),
    ("first_aider", "First aider"),
    ("mental_health_first_aider", "Mental health first aider"),
    ("mentor", "Mentor"),
    ("network_lead", "Network lead"),
    ("network_deputy_lead", "Network deputy lead"),
    ("cirrus_champion", "Cirrus champion"),
    ("health_wellbeing_champion", "Health & wellbeing champion"),
    ("fast_stream_rep", "Fast stream rep"),
    ("overseas_staff_rep", "Overseas staff rep"),
    ("digital_champion", "Digital champion"),
    ("information_manager", "Information manager"),
    ("independent_panel_member", "Independent panel member"),
    ("divisional_security_coordinator", "Divisional security coordinator"),
    ("ddat_champion", "DDaT champion"),
)


def insert_additional_roles_data(apps, schema_editor):
    AdditionalRole = apps.get_model("peoplefinder", "AdditionalRole")

    AdditionalRole.objects.bulk_create(
        [AdditionalRole(code=code, name=name) for code, name in ADDITIONAL_ROLES]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0023_auto_20210610_1247"),
    ]

    operations = [migrations.RunPython(insert_additional_roles_data)]
