# Generated by Django 3.2.4 on 2021-07-20 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0029_person_location_in_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
