# Generated by Django 3.2.4 on 2021-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0043_remove_null_from_person_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="legacy_slug",
            field=models.CharField(
                editable=False, max_length=80, null=True, unique=True
            ),
        ),
    ]
