# Generated by Django 3.2.4 on 2021-09-14 18:19

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0055_auto_20210914_1819"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"get_latest_by": "timestamp", "ordering": ["timestamp"]},
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="diff",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
