# Generated by Django 3.2.12 on 2022-03-04 12:26

import django_chunk_upload_handlers.clam_av
from django.db import migrations, models

import peoplefinder.models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0058_alter_auditlog_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePhotos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=-1, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "profile_photos",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="person",
            name="photo_small",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=peoplefinder.models.person_photo_small_path,
                validators=[
                    django_chunk_upload_handlers.clam_av.validate_virus_check_result
                ],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=peoplefinder.models.person_photo_path,
                validators=[
                    django_chunk_upload_handlers.clam_av.validate_virus_check_result
                ],
            ),
        ),
    ]
