# Generated by Django 3.2.12 on 2022-03-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0059_auto_20220304_1226"),
    ]

    operations = [
        migrations.CreateModel(
            name="Versions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.TextField()),
                ("item_id", models.IntegerField()),
                ("event", models.TextField()),
                ("whodunnit", models.TextField(blank=True, null=True)),
                ("object", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("object_changes", models.TextField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=-1, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=-1, null=True)),
            ],
            options={
                "db_table": "versions",
                "managed": False,
            },
        ),
    ]
