# Generated by Django 3.2.12 on 2022-03-07 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0059_auto_20220304_1226"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"get_latest_by": "timestamp", "ordering": ["timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={},
        ),
    ]
