# Generated by Django 3.2.12 on 2022-03-09 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0060_auto_20220307_1733"),
        ("peoplefinder", "0062_alter_legacyauditlog_options"),
    ]

    operations = []
