# Generated by Django 3.2.12 on 2022-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0063_merge_20220309_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="intermediate_languages",
            field=models.CharField(
                blank=True,
                help_text="Enter languages that you speak but aren't fluent in. Use a comma to separate them.",
                max_length=130,
                null=True,
                verbose_name="Which other languages do you speak?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="location_in_building",
            field=models.CharField(
                blank=True,
                help_text="Skip this question if you work in a Foreign and Commonwealth Office (FCO) building",
                max_length=130,
                null=True,
                verbose_name="Where in the building do you work?",
            ),
        ),
    ]
