# Generated by Django 3.2.12 on 2022-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0065_alter_person_secondary_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacyauditlog",
            name="automated",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
