# Generated by Django 3.2.12 on 2022-03-17 13:57

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django_chunk_upload_handlers.clam_av
from django.conf import settings
from django.db import migrations, models

import peoplefinder.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peoplefinder", "0068_data_person_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "legacy_slug",
                    models.CharField(
                        editable=False, max_length=80, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=80)),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter your own official work email address provided by the organisation you are directly employed by or contracted to.",
                        max_length=254,
                        verbose_name="Main work email address",
                    ),
                ),
                ("pronouns", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Enter the email address your colleagues should contact you on, for example, a jobshare or Private Office mailbox. This will be shown on your profile instead of your main work email address. Do not enter a personal email address, or a work email address that is not safe for official information.",
                        max_length=254,
                        null=True,
                        verbose_name="Contact email address",
                    ),
                ),
                (
                    "primary_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Enter your preferred contact telephone number. Include your country dialling code.",
                        max_length=42,
                        null=True,
                        verbose_name="Preferred contact number",
                    ),
                ),
                (
                    "secondary_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Enter an alternative contact telephone number. Include your country dialling code.",
                        max_length=160,
                        null=True,
                        verbose_name="Alternative contact number",
                    ),
                ),
                (
                    "town_city_or_region",
                    models.CharField(
                        blank=True,
                        help_text="For example, London",
                        max_length=78,
                        null=True,
                        verbose_name="Town, city or region",
                    ),
                ),
                (
                    "regional_building",
                    models.CharField(
                        blank=True,
                        max_length=130,
                        null=True,
                        verbose_name="UK regional building or location",
                    ),
                ),
                (
                    "international_building",
                    models.CharField(
                        blank=True,
                        max_length=110,
                        null=True,
                        verbose_name="International building or location",
                    ),
                ),
                (
                    "location_in_building",
                    models.CharField(
                        blank=True,
                        help_text="Skip this question if you work in a Foreign and Commonwealth Office (FCO) building",
                        max_length=130,
                        null=True,
                        verbose_name="Where in the building do you work?",
                    ),
                ),
                (
                    "do_not_work_for_dit",
                    models.BooleanField(
                        default=False,
                        verbose_name="My manager is not listed because I do not work for DIT",
                    ),
                ),
                (
                    "other_key_skills",
                    models.CharField(
                        blank=True,
                        help_text="Enter your skills. Use a comma to separate them.",
                        max_length=700,
                        null=True,
                        verbose_name="What other skills do you have?",
                    ),
                ),
                (
                    "fluent_languages",
                    models.CharField(
                        blank=True,
                        help_text="Enter languages that you are fluent in. Use a comma to separate them.",
                        max_length=100,
                        null=True,
                        verbose_name="Which languages do you speak fluently?",
                    ),
                ),
                (
                    "intermediate_languages",
                    models.CharField(
                        blank=True,
                        help_text="Enter languages that you speak but aren't fluent in. Use a comma to separate them.",
                        max_length=130,
                        null=True,
                        verbose_name="Which other languages do you speak?",
                    ),
                ),
                (
                    "other_learning_interests",
                    models.CharField(
                        blank=True,
                        help_text="Enter your interests. Use a comma to separate them.",
                        max_length=255,
                        null=True,
                        verbose_name="What other learning and development interests do you have?",
                    ),
                ),
                (
                    "other_additional_roles",
                    models.CharField(
                        blank=True,
                        help_text="Enter your roles or responsibilities. Use a comma to separate them.",
                        max_length=400,
                        null=True,
                        verbose_name="What other additional roles or responsibilities do you have?",
                    ),
                ),
                (
                    "previous_experience",
                    models.TextField(
                        blank=True,
                        help_text="List where you have worked before your current role.",
                        null=True,
                        verbose_name="Previous positions I have held",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=peoplefinder.models.person_photo_path,
                        validators=[
                            django_chunk_upload_handlers.clam_av.validate_virus_check_result
                        ],
                    ),
                ),
                (
                    "photo_small",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=peoplefinder.models.person_photo_small_path,
                        validators=[
                            django_chunk_upload_handlers.clam_av.validate_virus_check_result
                        ],
                    ),
                ),
                (
                    "additional_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select all that apply",
                        related_name="_peoplefinder_newperson_additional_roles_+",
                        to="peoplefinder.AdditionalRole",
                        verbose_name="Do you have any additional roles or responsibilities?",
                    ),
                ),
                (
                    "buildings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_peoplefinder_newperson_buildings_+",
                        to="peoplefinder.Building",
                        verbose_name="Where do you usually work?",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        # default=peoplefinder.models.Country.get_default_id,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="+",
                        to="peoplefinder.country",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="peoplefinder.grade",
                    ),
                ),
                (
                    "key_skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select all that apply",
                        related_name="_peoplefinder_newperson_key_skills_+",
                        to="peoplefinder.KeySkill",
                        verbose_name="What are your skills?",
                    ),
                ),
                (
                    "learning_interests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select all that apply",
                        related_name="_peoplefinder_newperson_learning_interests_+",
                        to="peoplefinder.LearningInterest",
                        verbose_name="What are your learning and development interests?",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="peoplefinder.person",
                    ),
                ),
                (
                    "networks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select all that apply",
                        related_name="_peoplefinder_newperson_networks_+",
                        to="peoplefinder.Network",
                        verbose_name="What networks do you belong to?",
                    ),
                ),
                (
                    "professions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select all that apply",
                        related_name="_peoplefinder_newperson_professions_+",
                        to="peoplefinder.Profession",
                        verbose_name="What professions do you belong to?",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workdays",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_peoplefinder_newperson_workdays_+",
                        to="peoplefinder.Workday",
                        verbose_name="Which days do you usually work?",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="newperson",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("pk", django.db.models.expressions.F("manager")), _negated=True
                ),
                name="new_manager_cannot_be_self",
            ),
        ),
    ]
