# Generated by Django 3.2.12 on 2022-03-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0076_merge_0064_auto_20220315_1622_0075_auto_20220318_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="edited_or_confirmed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
