# Generated by Django 3.2.13 on 2022-05-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0084_person_manager_cannot_be_self"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="fluent_languages",
            field=models.CharField(
                blank=True,
                help_text="Enter languages that you are fluent in. Use a comma to separate them.",
                max_length=200,
                null=True,
                verbose_name="Which languages do you speak fluently?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="intermediate_languages",
            field=models.CharField(
                blank=True,
                help_text="Enter languages that you speak but aren't fluent in. Use a comma to separate them.",
                max_length=200,
                null=True,
                verbose_name="Which other languages do you speak?",
            ),
        ),
    ]
