# Generated by Django 3.2.13 on 2022-05-23 13:15

from django.db import migrations


def insert_person_new_country(apps, schema_editor):
    Person = apps.get_model("peoplefinder", "Person")
    Country = apps.get_model("countries", "Country")

    all_people = Person.objects.select_related("country").all()
    country_lookup = Country.objects.all().in_bulk(field_name="iso_2_code")

    people_to_update = []

    for person in all_people:
        person.new_country = country_lookup[person.country.code]
        people_to_update.append(person)

    Person.objects.bulk_update(people_to_update, ["new_country"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0089_person_new_country"),
    ]

    operations = [migrations.RunPython(insert_person_new_country)]
