# Generated by Django 3.2.13 on 2022-06-30 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0094_alter_newnetwork_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="newnetwork",
            name="old_network",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peoplefinder.network",
            ),
        ),
    ]
