# Generated by Django 4.1.9 on 2023-07-04 11:10

from django.db import migrations, models

from peoplefinder.services.person import PersonService


def populate_profile_completion(apps, schema_editor):
    Person = apps.get_model("peoplefinder", "Person")
    for person in Person.objects.all():
        person.profile_completion = PersonService().get_profile_completion(
            person=person
        )
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0102_remove_person_manager_cannot_be_self_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="profile_completion",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(
            populate_profile_completion,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
