# Generated by Django 4.1.10 on 2023-07-07 16:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0103_person_profile_completion"),
    ]

    operations = [
        migrations.CreateModel(
            name="UkStaffLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=55)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="person",
            name="remote_working",
            field=models.CharField(
                choices=[
                    ("remote_worker", "I work primarily from home (remote worker)"),
                    ("split", "I split my time between home and the office(s)"),
                ],
                max_length=80,
                blank=True,
                null=True,
                verbose_name="Where do you usually work?",
            ),
        ),
        migrations.AddConstraint(
            model_name="ukstafflocation",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_location_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="ukstafflocation",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_location_name"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="uk_office_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Your base location as per your contract",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="peoplefinder.ukstafflocation",
                verbose_name="What is your office location?",
            ),
        ),
    ]
