# Generated by Django 4.1.7 on 2023-07-11 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0103_alter_person_email"),
        ("peoplefinder", "0103_person_profile_completion"),
    ]

    operations = []
