# Generated by Django 4.1.9 on 2023-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0103_person_profile_completion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                help_text="Choose your own official work email address provided by the organisation you are directly employed by or contracted to.",
                max_length=254,
                verbose_name="Main work email address",
            ),
        ),
    ]
