# Generated by Django 4.1.10 on 2023-07-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0105_ukstafflocation_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="name_pronunciation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
