# Generated by Django 4.1.10 on 2023-07-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0106_alter_person_remote_working"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="name_pronunciation",
            field=models.CharField(
                blank=True,
                help_text="<a href='https://workspace.trade.gov.uk/news-and-views/say-my-name/'>Tips for writing your name phonetically</a>",
                max_length=110,
                null=True,
                verbose_name="A phonetic representation of your name",
            ),
        ),
    ]
