# Generated by Django 4.1.10 on 2023-07-26 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0106_alter_person_remote_working"),
        ("peoplefinder", "0106_person_name_pronunciation"),
    ]

    operations = []
