# Generated by Django 4.1.10 on 2023-07-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0107_merge_20230726_1628"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name_pronunciation",
            field=models.CharField(
                blank=True,
                max_length=110,
                null=True,
                verbose_name="A phonetic representation of your name",
            ),
        ),
    ]
