# Generated by Django 4.1.10 on 2023-08-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "peoplefinder",
            "0107_person_name_pronunciation_alter_person_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Complete if you want to show a different email address on your profile for example a jobshare or Private Office mailbox. Do not enter a personal email address, or work email address that is not safe for official information.",
                max_length=254,
                null=True,
                verbose_name="Preferred email address",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                help_text="The work email address provided by the organisation you are directly employed by or contracted to. This is the email you use to log into Digital Workspace.",
                max_length=254,
                verbose_name="Main work email address",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                help_text="If you enter a preferred name below, this name will be hidden to others",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="international_building",
            field=models.CharField(
                blank=True,
                help_text="Complete if you work outside the UK.",
                max_length=110,
                null=True,
                verbose_name="International location",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="location_in_building",
            field=models.CharField(
                blank=True,
                help_text="If you sit in a particular area, you can let colleagues know here.",
                max_length=130,
                null=True,
                verbose_name="Location in the building",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name_pronunciation",
            field=models.CharField(
                blank=True,
                help_text="A phonetic representation of your name.<br><a class='govuk-link' href='/news-and-views/say-my-name/' target='_blank' rel='noreferrer'>Tips for writing your name phonetically</a>",
                max_length=200,
                null=True,
                verbose_name="How to pronounce your full name",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="primary_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Include your country dialling code.",
                max_length=42,
                null=True,
                verbose_name="Contact number",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="secondary_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Include your country dialling code.",
                max_length=160,
                null=True,
                verbose_name="Alternative contact number",
            ),
        ),
    ]
