# Generated by Django 4.1.10 on 2023-09-05 13:06

from django.db import migrations, models


def populate_preferred_first_name(apps, schema_editor):
    """
    Update all Profile models preferred_first_name with the profile.first_name
    """
    Person = apps.get_model("peoplefinder", "Person")
    Person.objects.update(preferred_first_name=models.F("first_name"))


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0108_alter_person_contact_email_alter_person_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="preferred_first_name",
            field=models.CharField(
                help_text="How you would prefer to be called, for example a shortened version of your name. This will appear on your profile.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_preferred_first_name, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="person",
            name="preferred_first_name",
            field=models.CharField(
                help_text="How you would prefer to be called, for example a shortened version of your name. This will appear on your profile.",
                max_length=200,
            ),
        ),
        # Use SQL to update the first_name field on the Person model with the
        # first_name field on the User model (if they are different)
        migrations.RunSQL(
            # We use SQL instead of the ORM here for simplicity and performance.
            sql="""
                UPDATE peoplefinder_person
                SET first_name = user_user.first_name
                FROM user_user
                WHERE peoplefinder_person.user_id = user_user.id
                AND peoplefinder_person.first_name <> user_user.first_name;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
