# Generated by Django 4.1.10 on 2023-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0109_person_preferred_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                help_text="Choose your own official work email address provided by the organisation you are directly employed by or contracted to. This is the email you use to log into Digital Workspace.",
                max_length=254,
                verbose_name="Main work email address",
            ),
        ),
    ]
