# Generated by Django 4.1.10 on 2023-09-05 13:06

from django.db import migrations, models


def populate_contact_email(apps, schema_editor):
    """
    Set the contact email to the email address if it is blank.
    """
    Person = apps.get_model("peoplefinder", "Person")
    Person.objects.exclude(contact_email__isnull=False).update(
        contact_email=models.F("email"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0109_person_preferred_first_name"),
    ]

    operations = [
        migrations.RunPython(
            populate_contact_email,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
