# Generated by Django 4.1.10 on 2023-09-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0110_person_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="The work email you want people to contact you on.",
                max_length=254,
                null=True,
                verbose_name="Email address",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="primary_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter the country's dialling code in place of the first 0. The UK's dialling code is +44.",
                max_length=42,
                null=True,
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="secondary_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter the country's dialling code in place of the first 0. The UK's dialling code is +44.",
                max_length=160,
                null=True,
                verbose_name="Alternative phone number",
            ),
        ),
    ]
