# Generated by Django 4.1.10 on 2023-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0111_alter_person_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="usual_office_days",
            field=models.CharField(
                blank=True,
                help_text="e.g. I usually come in on Mondays and Wednesdays",
                max_length=200,
                null=True,
            ),
        ),
    ]
