# Generated by Django 4.1.10 on 2023-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0111_alter_person_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="preferred_first_name",
            field=models.CharField(
                blank=True,
                help_text="How you would prefer to be called, for example a shortened version of your name. This will appear on your profile.",
                max_length=200,
                null=True,
            ),
        ),
    ]
