# Generated by Django 4.1.10 on 2023-09-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0112_alter_person_preferred_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="usual_office_days",
            field=models.CharField(
                blank=True,
                help_text="For example: I usually come in on Mondays and Wednesdays",
                max_length=200,
                null=True,
                verbose_name="What days do you usually come in to the office?",
            ),
        ),
    ]
