# Generated by Django 4.1.10 on 2023-09-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0113_person_usual_office_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="The work email you want people to contact you on",
                max_length=254,
                null=True,
                verbose_name="Email address",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="international_building",
            field=models.CharField(
                blank=True,
                help_text="Complete if you work outside the UK",
                max_length=110,
                null=True,
                verbose_name="International location",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="location_in_building",
            field=models.CharField(
                blank=True,
                help_text="If you sit in a particular area, you can let colleagues know here",
                max_length=130,
                null=True,
                verbose_name="Location in the building",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name_pronunciation",
            field=models.CharField(
                blank=True,
                help_text="A phonetic representation of your name<br><a class='govuk-link' href='/news-and-views/say-my-name/' target='_blank' rel='noreferrer'>Tips for writing your name phonetically</a>",
                max_length=200,
                null=True,
                verbose_name="How to pronounce your full name",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="previous_experience",
            field=models.TextField(
                blank=True,
                help_text="List where you have worked before your current role",
                null=True,
                verbose_name="Previous positions I have held",
            ),
        ),
    ]
