# Generated by Django 4.1.10 on 2023-09-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0114_alter_person_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="fluent_languages",
            field=models.CharField(
                blank=True,
                help_text="Use a comma to separate the languages. For example: French, Polish, Ukrainian",
                max_length=200,
                null=True,
                verbose_name="Which languages are you fluent in?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="intermediate_languages",
            field=models.CharField(
                blank=True,
                help_text="These are languages you speak and write but are not fluent in",
                max_length=200,
                null=True,
                verbose_name="Which other languages do you speak?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="preferred_first_name",
            field=models.CharField(
                blank=True,
                help_text="This name appears on your profile. Colleagues can search for you using either of your first names",
                max_length=200,
                null=True,
            ),
        ),
    ]
