# Generated by Django 4.1.10 on 2023-09-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0115_alter_person_fluent_languages_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ukstafflocation",
            name="unique_location_name",
        ),
        migrations.AlterField(
            model_name="ukstafflocation",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
