# Generated by Django 4.1.10 on 2023-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0115_alter_person_fluent_languages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="preferred_first_name",
            field=models.CharField(
                blank=True,
                help_text="This name appears on your profile. Colleagues can search for you using either of your first names",
                max_length=200,
                null=True,
            ),
        ),
    ]
