# Generated by Django 4.1.10 on 2023-09-05 13:06

from django.db import migrations, models


def uk_staff_locations_DIT_to_DBT(apps, schema_editor):
    """
    Update all UK Staff Locations from DIT/BEIS to DBT.
    """
    Person = apps.get_model("peoplefinder", "Person")
    UkStaffLocation = apps.get_model("peoplefinder", "UkStaffLocation")
    profiles_with_old_location = Person.objects.filter(
        uk_office_location__organisation__in=[
            "Department for International Trade",
            "Department for Business, Energy and Industrial Strategy",
        ]
    )

    update_list = []
    for profile in profiles_with_old_location:
        old_office_location = profile.uk_office_location
        try:
            new_office_location = UkStaffLocation.objects.get(
                name=old_office_location.name,
                city=old_office_location.city,
                organisation="Department for Business and Trade",
            )
        except UkStaffLocation.DoesNotExist:
            continue
        profile.uk_office_location = new_office_location
        update_list.append(profile)

    Person.objects.bulk_update(update_list, ["uk_office_location"])


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0116_remove_ukstafflocation_unique_location_name_and_more"),
    ]

    operations = [
        migrations.RunPython(
            uk_staff_locations_DIT_to_DBT,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
