# Generated by Django 4.1.10 on 2023-10-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0117_uk_staff_locations_DIT_to_DBT"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                help_text="This is the email you want to receive official communications from the department as well as notifications for Digital Workspace, Data Workspace. You can still log in to services with any of these emails. It does not show on your profile, unless you have set it as your contact email",
                max_length=254,
                verbose_name="How we contact you",
            ),
        ),
    ]
