# Generated by Django 4.1.10 on 2023-10-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0117_uk_staff_locations_DIT_to_DBT"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                help_text="We will send Digital Workspace notifications to this email",
                max_length=254,
                verbose_name="How we contact you",
            ),
        ),
    ]
