# Generated by Django 4.1.13 on 2023-11-16 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0118_alter_person_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "permissions": [
                    ("can_view_inactive_profiles", "Can view inactive profiles")
                ]
            },
        ),
    ]
