# Generated by Django 4.2.11 on 2024-04-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0119_alter_person_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="peoplefinder.person",
            ),
        ),
    ]
