# Generated by Django 4.2.11 on 2024-04-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0120_add_honours_champions"),
        ("peoplefinder", "0120_alter_person_manager"),
    ]

    operations = []
