# Generated by Django 4.2.17 on 2024-12-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0122_add_ical_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="ukstafflocation",
            name="building_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
