# Generated by Django 4.1.9 on 2023-07-04 11:10

from django.db import migrations, models

from peoplefinder.services.person import PersonService


def update_profile_completion(apps, schema_editor):
    Person = apps.get_model("peoplefinder", "Person")
    for person in Person.objects.all():
        person.profile_completion = PersonService().get_profile_completion(
            person=person
        )
        person.save(update_fields=["profile_completion"])


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0123_ukstafflocation_building_name"),
    ]

    operations = [
        migrations.RunPython(
            update_profile_completion,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
