# Generated by Django 5.1.8 on 2025-04-29 11:33

from django.db import migrations


def update_grade_ordering_data(apps, schema_editor):
    Grade = apps.get_model("peoplefinder", "Grade")
    Grade.objects.filter(code="fco_s1").update(ordering=12)
    Grade.objects.filter(code="fco_s2").update(ordering=12)
    Grade.objects.filter(code="fco_s3").update(ordering=12)
    Grade.objects.filter(code="apprentice").update(ordering=12)
    Grade.objects.filter(code="fast_stream").update(ordering=12)
    Grade.objects.filter(code="fast_track").update(ordering=12)
    Grade.objects.filter(code="non_graded_special_advisor").update(ordering=12)
    Grade.objects.filter(code="non_graded_contractor").update(ordering=12)
    Grade.objects.filter(code="non_graded_secondee").update(ordering=12)
    Grade.objects.filter(code="non_graded_post").update(ordering=12)
    Grade.objects.filter(code="admin_assistant").update(ordering=11)
    Grade.objects.filter(code="admin_officer").update(ordering=10)
    Grade.objects.filter(code="executive_officer").update(ordering=9)
    Grade.objects.filter(code="higher_executive_officer").update(ordering=8)
    Grade.objects.filter(code="senior_executive_officer").update(ordering=7)
    Grade.objects.filter(code="grade_7").update(ordering=6)
    Grade.objects.filter(code="grade_6").update(ordering=5)
    Grade.objects.filter(code="scs_1").update(ordering=4)
    Grade.objects.filter(code="scs_2").update(ordering=3)
    Grade.objects.filter(code="scs_3").update(ordering=2)
    Grade.objects.filter(code="scs_4").update(ordering=1)


def reverse_update_grade_ordering_data(apps, schema_editor):
    Grade = apps.get_model("peoplefinder", "Grade")
    Grade.objects.all().update(ordering=None)


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0127_alter_person_options"),
    ]

    operations = [
        migrations.RunPython(
            code=update_grade_ordering_data,
            reverse_code=reverse_update_grade_ordering_data,
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={"ordering": ["ordering"]},
        ),
    ]
