# Generated by Django 5.1.8 on 2025-04-25 11:07

import core.field_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0127_alter_person_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalrole",
            name="code",
            field=core.field_models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="additionalrole",
            name="name",
            field=core.field_models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=core.field_models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                ],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="code",
            field=core.field_models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="building",
            name="name",
            field=core.field_models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="grade",
            name="code",
            field=core.field_models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="grade",
            name="name",
            field=core.field_models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="keyskill",
            name="code",
            field=core.field_models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="keyskill",
            name="name",
            field=core.field_models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="learninginterest",
            name="code",
            field=core.field_models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="learninginterest",
            name="name",
            field=core.field_models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="legacyauditlog",
            name="action",
            field=core.field_models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                ],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="legacyauditlog",
            name="object",
            field=core.field_models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="legacyauditlog",
            name="object_changes",
            field=core.field_models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="network",
            name="code",
            field=core.field_models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="network",
            name="name",
            field=core.field_models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=core.field_models.CharField(
                help_text="If you enter a preferred name below, this name will be hidden to others",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="fluent_languages",
            field=core.field_models.CharField(
                blank=True,
                help_text="Use a comma to separate the languages. For example: French, Polish, Ukrainian",
                max_length=200,
                null=True,
                verbose_name="Which languages are you fluent in?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="ical_token",
            field=core.field_models.CharField(
                blank=True,
                max_length=80,
                null=True,
                verbose_name="Individual token for iCal feeds",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="intermediate_languages",
            field=core.field_models.CharField(
                blank=True,
                help_text="These are languages you speak and write but are not fluent in",
                max_length=200,
                null=True,
                verbose_name="Which other languages do you speak?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="international_building",
            field=core.field_models.CharField(
                blank=True,
                help_text="Complete if you work outside the UK",
                max_length=110,
                null=True,
                verbose_name="International location",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=core.field_models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="person",
            name="legacy_slug",
            field=core.field_models.CharField(
                editable=False, max_length=80, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="legacy_sso_user_id",
            field=core.field_models.CharField(
                editable=False, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="location_in_building",
            field=core.field_models.CharField(
                blank=True,
                help_text="If you sit in a particular area, you can let colleagues know here",
                max_length=130,
                null=True,
                verbose_name="Location in the building",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name_pronunciation",
            field=core.field_models.CharField(
                blank=True,
                help_text="A phonetic representation of your name<br><a class='govuk-link' href='/news-and-views/say-my-name/' target='_blank' rel='noreferrer'>Tips for writing your name phonetically</a>",
                max_length=200,
                null=True,
                verbose_name="How to pronounce your full name",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="other_additional_roles",
            field=core.field_models.CharField(
                blank=True,
                help_text="Enter your roles or responsibilities. Use a comma to separate them.",
                max_length=400,
                null=True,
                verbose_name="What other additional roles or responsibilities do you have?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="other_key_skills",
            field=core.field_models.CharField(
                blank=True,
                help_text="Enter your skills. Use a comma to separate them.",
                max_length=700,
                null=True,
                verbose_name="What other skills do you have?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="other_learning_interests",
            field=core.field_models.CharField(
                blank=True,
                help_text="Enter your interests. Use a comma to separate them.",
                max_length=255,
                null=True,
                verbose_name="What other learning and development interests do you have?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="preferred_first_name",
            field=core.field_models.CharField(
                blank=True,
                help_text="This name appears on your profile. Colleagues can search for you using either of your first names",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="previous_experience",
            field=core.field_models.TextField(
                blank=True,
                help_text="List where you have worked before your current role",
                null=True,
                verbose_name="Previous positions I have held",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="primary_phone_number",
            field=core.field_models.CharField(
                blank=True,
                help_text="Enter the country's dialling code in place of the first 0. The UK's dialling code is +44.",
                max_length=42,
                null=True,
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="pronouns",
            field=core.field_models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="regional_building",
            field=core.field_models.CharField(
                blank=True,
                max_length=130,
                null=True,
                verbose_name="UK regional building or location",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="remote_working",
            field=core.field_models.CharField(
                blank=True,
                choices=[
                    ("office_worker", "I work primarily from the office"),
                    ("remote_worker", "I work primarily from home (remote worker)"),
                    ("split", "I split my time between home and the office"),
                ],
                max_length=80,
                null=True,
                verbose_name="Where do you usually work?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="secondary_phone_number",
            field=core.field_models.CharField(
                blank=True,
                help_text="Enter the country's dialling code in place of the first 0. The UK's dialling code is +44.",
                max_length=160,
                null=True,
                verbose_name="Alternative phone number",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="town_city_or_region",
            field=core.field_models.CharField(
                blank=True,
                help_text="For example, London",
                max_length=78,
                null=True,
                verbose_name="Town, city or region",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="usual_office_days",
            field=core.field_models.CharField(
                blank=True,
                help_text="For example: I usually come in on Mondays and Wednesdays",
                max_length=200,
                null=True,
                verbose_name="What days do you usually come in to the office?",
            ),
        ),
        migrations.AlterField(
            model_name="profession",
            name="code",
            field=core.field_models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="profession",
            name="name",
            field=core.field_models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="team",
            name="abbreviation",
            field=core.field_models.CharField(
                blank=True,
                help_text="A short form of the team name, up to 10 characters. For example DDaT.",
                max_length=20,
                null=True,
                verbose_name="Team acronym or initials",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=core.field_models.TextField(
                default="Find out who is in the team and their contact details.\n\nYou can update this description, by [updating your team information](https://workspace.trade.gov.uk/working-at-dbt/how-do-i/update-my-team-information-on-people-finder/).\n",
                help_text="What does this team do? Use Markdown to add lists and links. Enter up to 1500 characters.",
                verbose_name="Team description",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="leaders_ordering",
            field=core.field_models.CharField(
                blank=True,
                choices=[("alphabetical", "Alphabetical"), ("custom", "Custom")],
                default="alphabetical",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=core.field_models.CharField(
                help_text="The full name of this team (e.g. Digital, Data and Technology)",
                max_length=255,
                verbose_name="Team name (required)",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="job_title",
            field=core.field_models.CharField(
                help_text="Enter your role in this team", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="ukstafflocation",
            name="building_name",
            field=core.field_models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="ukstafflocation",
            name="city",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ukstafflocation",
            name="code",
            field=core.field_models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="ukstafflocation",
            name="name",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ukstafflocation",
            name="organisation",
            field=core.field_models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="workday",
            name="code",
            field=core.field_models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="workday",
            name="name",
            field=core.field_models.CharField(max_length=9),
        ),
    ]
