# Generated by Django 5.1.8 on 2025-05-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0128_alter_grade_options_and_update_ordering_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["grade", "last_name", "first_name"],
                "permissions": [
                    ("can_view_inactive_profiles", "Can view inactive profiles")
                ],
            },
        ),
    ]
