# Generated by Django 5.1.9 on 2025-05-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0129_alter_person_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBTSector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("exists_in_last_import", models.BooleanField(default=True)),
                ("sector_id", models.CharField(max_length=255, unique=True)),
                (
                    "full_sector_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sector_cluster_name_april_2023_onwards",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sector_cluster_name_before_april_2023",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sector_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sub_sector_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sub_sub_sector_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["sector_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sector_id",), name="unique_sector_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UKOfficeLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("exists_in_last_import", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("organisation", models.CharField(max_length=255)),
                ("building_name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="unique_office_location_code"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="person",
            name="new_uk_office_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Your base location as per your contract",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="peoplefinder.ukofficelocation",
                verbose_name="What is your office location?",
            ),
        ),
    ]
