# Generated by Django 5.1.8 on 2025-05-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0129_alter_person_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["grade", "first_name", "last_name"],
                "permissions": [
                    ("can_view_inactive_profiles", "Can view inactive profiles")
                ],
            },
        ),
    ]
