# Generated by Django 5.1.9 on 2025-05-28 15:59

from django.db import migrations
from datetime import datetime


def insert_data_to_new_fields(apps, schema_editor):
    Person = apps.get_model("peoplefinder", "Person")
    for person in Person.objects.all():
        if person.uk_office_location:
            person.based_overseas == False
        person.start_date == person.created_at
        person.save(update_fields=["start_date", "based_overseas"])


def reverse_insert_data_to_new_fields(apps, schema_editor):
    Person = apps.get_model("peoplefinder", "Person")
    Person.objects.all().update(
        based_overseas=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("peoplefinder", "0130_person_absence_contact_person_absence_end_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=insert_data_to_new_fields,
            reverse_code=reverse_insert_data_to_new_fields,
        ),
    ]
