# Generated by Django 3.0.7 on 2020-09-08 05:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_auto_20200903_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeFromSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('alternative', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PagePin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_pins', to='content.ContentPage')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_pages', to='search.Pin')),
            ],
            options={
                'unique_together': {('page', 'pin')},
            },
        ),
    ]
