# Generated by Django 3.0.7 on 2020-09-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagePin',
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
    ]
