# Generated by Django 3.2.17 on 2023-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_historicalexcludefromsearch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalexcludefromsearch",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical exclude from search",
                "verbose_name_plural": "historical exclude from searchs",
            },
        ),
        migrations.AlterField(
            model_name="historicalexcludefromsearch",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
