# Generated by Django 3.0.7 on 2020-09-09 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_stopword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StopWord',
        ),
        migrations.DeleteModel(
            name='Synonym',
        ),
    ]
