# Generated by Django 3.2.4 on 2021-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_historicaluser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('legacy_sso_user_id',), name='unique_legacy_sso_user_id'),
        ),
    ]
