# Generated by Django 3.2.4 on 2021-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210819_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_using_peoplefinder_v2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_using_peoplefinder_v2',
            field=models.BooleanField(default=False),
        ),
    ]
