# Generated by Django 3.2.13 on 2022-05-19 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_auto_20210823_1442"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="is_using_peoplefinder_v2",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_using_peoplefinder_v2",
        ),
    ]
