# Generated by Django 3.2.16 on 2023-01-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_auto_20220519_1708"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="enable_v2_search",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="enable_v2_search",
            field=models.BooleanField(default=False),
        ),
    ]
