# Generated by Django 3.2.17 on 2023-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_auto_20230130_1438"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaluser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
            },
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
