# Generated by Django 3.0.7 on 2020-08-11 11:42

import content.blocks
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('legacy_guid', models.CharField(blank=True, help_text='Wordpress GUID', max_length=255)),
                ('legacy_content', models.TextField(blank=True, help_text='Legacy content, pre-conversion')),
                ('body', wagtail.core.fields.StreamField([('heading2', content.blocks.Heading2Block()), ('heading3', content.blocks.Heading3Block()), ('text_section', content.blocks.TextBlock(blank=True, features=['bold', 'italic', 'ol', 'ul', 'link', 'document-link'], help_text='Some text to describe what this section is about (will be\n            displayed above the list of child pages)')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('isdecorative', wagtail.core.blocks.BooleanBlock(help_text='\n        Tick if this image is entirely decorative and does not include\n        important content. This will hide the image from users using\n        screen readers.\n        ', label='Is this a decorative image?', required=False)), ('alt', wagtail.core.blocks.CharBlock(help_text='\n        Read out by screen readers or displayed if an image does not load\n        or if images have been switched off.\n\n        Unless this is a decorative image, it MUST have alt text that\n        tells people what information the image provides, describes its\n        content and function, and is specific, meaningful and concise.\n        ', label='Alt text', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='\n        Optional text displayed under the image on the page to provide\n        context.\n        ', required=False))])), ('internal_media', wagtail.core.blocks.StructBlock([('media_file', content.blocks.MediaChooserBlock())])), ('data_table', content.blocks.DataTableBlock(help_text='ONLY USE THIS FOR TABLULAR DATA, NOT FOR FORMATTING'))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewsHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PoliciesAndGuidance',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToolsHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PageWithTopics',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intro', wagtail.core.fields.StreamField([('heading2', content.blocks.Heading2Block()), ('heading3', content.blocks.Heading3Block()), ('text_section', content.blocks.TextBlock(blank=True, features=['bold', 'italic', 'ol', 'ul', 'link', 'document-link'], help_text='Some text to describe what this section is about (will be\n            displayed above the list of child pages)')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('isdecorative', wagtail.core.blocks.BooleanBlock(help_text='\n        Tick if this image is entirely decorative and does not include\n        important content. This will hide the image from users using\n        screen readers.\n        ', label='Is this a decorative image?', required=False)), ('alt', wagtail.core.blocks.CharBlock(help_text='\n        Read out by screen readers or displayed if an image does not load\n        or if images have been switched off.\n\n        Unless this is a decorative image, it MUST have alt text that\n        tells people what information the image provides, describes its\n        content and function, and is specific, meaningful and concise.\n        ', label='Alt text', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='\n        Optional text displayed under the image on the page to provide\n        context.\n        ', required=False))])), ('internal_media', wagtail.core.blocks.StructBlock([('media_file', content.blocks.MediaChooserBlock())])), ('data_table', content.blocks.DataTableBlock(help_text='ONLY USE THIS FOR TABLULAR DATA, NOT FOR FORMATTING'))])),
                ('themes', models.ManyToManyField(to='content.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.pagewithtopics',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.PageWithTopics')),
                ('excerpt', models.CharField(blank=True, max_length=250)),
                ('preview_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.pagewithtopics',),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.pagewithtopics',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('pagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.PageWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.pagewithtopics',),
        ),
        migrations.AddField(
            model_name='pagewithtopics',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(to='content.Topic'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(null=True)),
                ('content', models.CharField(max_length=255)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Comment')),
                ('news_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.NewsPage')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPageNewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_pages', to='content.NewsCategory')),
                ('news_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_categories', to='content.NewsPage')),
            ],
            options={
                'unique_together': {('news_page', 'news_category')},
            },
        ),
    ]
