# Generated by Django 3.0.7 on 2020-06-23 08:51

import content.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('legacy_guid', models.CharField(help_text='Wordpress GUID', max_length=255)),
                ('legacy_content', models.TextField(blank=True, help_text='Legacy content, pre-conversion')),
                ('excerpt', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.core.fields.StreamField([('heading', content.blocks.HeadingBlock()), ('text_section', content.blocks.TextBlock(blank=True, features=['bold', 'italic', 'ol', 'ul', 'link', 'document-link'], help_text='Some text to describe what this section is about (will be\n            displayed above the list of child pages)')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('isdecorative', wagtail.core.blocks.BooleanBlock(help_text='\n        Tick if this image is entirely decorative and does not include\n        important content. This will hide the image from users using\n        screen readers.\n        ', label='Is this a decorative image?', required=False)), ('alt', wagtail.core.blocks.CharBlock(help_text='\n        Read out by screen readers or displayed if an image does not load\n        or if images have been switched off.\n\n        Unless this is a decorative image, it MUST have alt text that\n        tells people what information the image provides, describes its\n        content and function, and is specific, meaningful and concise.\n        ', label='Alt text', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='\n        Optional text displayed under the image on the page to provide\n        context.\n        ', required=False))])), ('internal_media', wagtail.core.blocks.StructBlock([('media_file', content.blocks.MediaChooserBlock())])), ('data_table', content.blocks.DataTableBlock(help_text='ONLY USE THIS FOR TABLULAR DATA, NOT FOR FORMATTING'))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
