# Generated by Django 2.2.8 on 2019-12-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindexpage',
            name='excerpt',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='excerpt',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
