# Generated by Django 3.0.7 on 2020-07-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='tags',
            new_name='news_categories',
        ),
    ]
