# Generated by Django 3.0.7 on 2020-11-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="excluded_phrases",
            field=models.CharField(
                blank=True,
                help_text="A comma separated list of excluded keywords and phrases. Do not use quotes for phrases. The page will be removed from search results for these terms",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="pinned_phrases",
            field=models.CharField(
                blank=True,
                help_text="A comma separated list of pinned keywords and phrases. Do not use quotes for phrases. The page will be pinned to the first page of search results for these terms.",
                max_length=1000,
                null=True,
            ),
        ),
    ]
