# Generated by Django 3.0.7 on 2020-07-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsCategoryHome',
        ),
    ]
