# Generated by Django 3.0.7 on 2020-09-18 06:40

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='search_exclusions',
            field=modelcluster.fields.ParentalManyToManyField(to='content.SearchResultExclusion'),
        ),
    ]
