# Generated by Django 3.0.7 on 2020-06-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='legacy_guid',
            field=models.CharField(blank=True, help_text='Wordpress GUID', max_length=255),
        ),
    ]
