# Generated by Django 3.0.7 on 2020-09-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0002_auto_20200918_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='search_exclusions',
        ),
        migrations.CreateModel(
            name='SearchExclusionPageLookUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('search_result_exclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SearchResultExclusion')),
            ],
        ),
    ]
