# Generated by Django 2.2.8 on 2019-12-19 21:56

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20191218_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindexpage',
            name='excerpt',
            field=models.CharField(help_text="Short summary of what this section is about (will be\n        displayed in the list of children on this page's parent page)", max_length=250),
        ),
        migrations.AlterField(
            model_name='contentindexpage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Some text to describe what this section is about (will be\n        displayed above the list of child pages)'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('text_content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'document-link'])), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
