# Generated by Django 3.0.7 on 2020-09-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200813_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='legacy_content',
            field=models.TextField(blank=True, help_text='Legacy content, pre-conversion', null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='legacy_guid',
            field=models.CharField(blank=True, help_text='Wordpress GUID', max_length=255, null=True),
        ),
    ]
