# Generated by Django 3.0.7 on 2020-07-29 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='legacy_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Comment'),
            preserve_default=False,
        ),
    ]
