# Generated by Django 3.0.7 on 2020-11-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_auto_20201113_0844"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAlertBanner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_text", models.CharField(max_length=255)),
                ("activated", models.BooleanField(default=False)),
            ],
        ),
    ]
