# Generated by Django 3.0.7 on 2020-09-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20200903_0725'),
        ('content', '0003_linklistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkListItem',
        ),
    ]
