# Generated by Django 3.0.7 on 2020-09-08 05:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.blocks.field_block
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200903_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='pinned_phrases',
            field=wagtail.core.fields.StreamField([('phrase', wagtail.core.blocks.ListBlock(wagtail.core.blocks.field_block.CharBlock))]),
            preserve_default=False,
        ),
    ]
