# Generated by Django 3.0.7 on 2020-09-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0003_auto_20200921_0906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchResultExclusion',
            new_name='SearchKeywordOrPhrase',
        ),
        migrations.CreateModel(
            name='SearchPinPageLookUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('search_result_exclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SearchKeywordOrPhrase')),
            ],
        ),
    ]
