# Generated by Django 3.0.7 on 2020-11-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("working_at_dit", "0002_auto_20201113_0844"),
        ("content", "0004_sitealertbanner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HowDoI",
            new_name="HowDoIPreview",
        ),
    ]
