# Generated by Django 3.0.7 on 2020-09-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200921_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpinpagelookup',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_pin_page_look_ups', to='content.ContentPage'),
            preserve_default=False,
        ),
    ]
