# Generated by Django 3.0.7 on 2020-09-08 06:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contentpage_pinned_phrases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='pinned_phrases',
            field=wagtail.core.fields.StreamField([('phrase', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(blank=True)))]),
        ),
    ]
