# Generated by Django 3.0.7 on 2020-06-19 10:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200617_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Some text to describe what this section is about (will be\n        displayed above the list of child pages)'),
        ),
    ]
