# Generated by Django 3.0.7 on 2020-09-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_searchpinpagelookup_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchpinpagelookup',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='searchpinpagelookup',
            name='object_id',
        ),
    ]
