# Generated by Django 3.0.7 on 2020-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200729_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='legacy_id',
            field=models.IntegerField(null=True),
        ),
    ]
