# Generated by Django 3.0.7 on 2020-06-25 03:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200624_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategorytag',
            options={'verbose_name': 'news tag', 'verbose_name_plural': 'news tags'},
        ),
        migrations.RemoveField(
            model_name='newscategorytag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='newscategorytag',
            name='tag',
        ),
        migrations.AddField(
            model_name='newscategorytag',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newscategorytag',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaggedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_news_items', to='content.NewsPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_news', to='content.NewsCategoryTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='newspage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='content.TaggedNews', to='content.NewsCategoryTag', verbose_name='Tags'),
        ),
    ]
