# Generated by Django 3.0.7 on 2020-11-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_auto_20201114_0341"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuickLinks",
            new_name="QuickLink",
        ),
    ]
