# Generated by Django 3.0.7 on 2020-09-21 10:59

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200921_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpinpagelookup',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_pin_page_look_ups', to='content.ContentPage'),
        ),
    ]
