# Generated by Django 3.0.7 on 2020-11-16 03:12

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
from django.db import migrations

import content.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_auto_20201114_0422"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quicklink",
            name="link_to",
        ),
        migrations.RemoveField(
            model_name="whatspopular",
            name="link_to",
        ),
        migrations.RemoveField(
            model_name="whatspopular",
            name="preview_image",
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    ("heading2", content.blocks.Heading2Block()),
                    ("heading3", content.blocks.Heading3Block()),
                    ("heading4", content.blocks.Heading4Block()),
                    ("heading5", content.blocks.Heading5Block()),
                    (
                        "text_section",
                        content.blocks.TextBlock(
                            blank=True,
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                                "anchor-identifier",
                            ],
                            help_text="Some text to describe what this section is about (will be\n            displayed above the list of child pages)",
                        ),
                    ),
                    (
                        "image",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "isdecorative",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="\n        Tick if this image is entirely decorative and does not include\n        important content. This will hide the image from users using\n        screen readers.\n        ",
                                        label="Is this a decorative image?",
                                        required=False,
                                    ),
                                ),
                                (
                                    "alt",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="\n        Read out by screen readers or displayed if an image does not load\n        or if images have been switched off.\n\n        Unless this is a decorative image, it MUST have alt text that\n        tells people what information the image provides, describes its\n        content and function, and is specific, meaningful and concise.\n        ",
                                        label="Alt text",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="\n        Optional text displayed under the image on the page to provide\n        context.\n        ",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "internal_media",
                        wagtail.core.blocks.StructBlock(
                            [("media_file", content.blocks.MediaChooserBlock())]
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [("video", wagtail.embeds.blocks.EmbedBlock())],
                            help_text="Video embedding",
                        ),
                    ),
                    (
                        "data_table",
                        content.blocks.DataTableBlock(
                            help_text="ONLY USE THIS FOR TABLULAR DATA, NOT FOR FORMATTING"
                        ),
                    ),
                ]
            ),
        ),
        migrations.DeleteModel(
            name="HowDoIPreview",
        ),
        migrations.DeleteModel(
            name="QuickLink",
        ),
        migrations.DeleteModel(
            name="WhatsPopular",
        ),
    ]
