# Generated by Django 3.0.7 on 2020-09-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0007_auto_20200921_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchpinpagelookup',
            name='page',
        ),
        migrations.AddField(
            model_name='searchpinpagelookup',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchpinpagelookup',
            name='object_id',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
