# Generated by Django 3.0.7 on 2020-09-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20200921_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchexclusionpagelookup',
            old_name='search_result_exclusion',
            new_name='search_keyword_or_phrase',
        ),
        migrations.RenameField(
            model_name='searchpinpagelookup',
            old_name='search_result_exclusion',
            new_name='search_keyword_or_phrase',
        ),
    ]
