# Generated by Django 3.0.7 on 2020-08-04 09:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_create_topic_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBase',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
                ('excerpt', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='PageWithTheme',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='PoliciesAndGuidance',
            fields=[
                ('contentpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentpage',),
        ),
        migrations.CreateModel(
            name='ThemeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'theme tag',
                'verbose_name_plural': 'theme tags',
            },
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='contentpage_ptr',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='contentpage_ptr',
        ),
        migrations.AlterField(
            model_name='taggednews',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_page', to='content.NewsPage'),
        ),
        migrations.AlterField(
            model_name='taggednews',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_tag', to='content.NewsCategoryTag'),
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('pagewiththeme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.PageWithTheme')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.pagewiththeme',),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('pagewiththeme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.PageWithTheme')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.pagewiththeme',),
        ),
        migrations.CreateModel(
            name='TaggedTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_page', to='content.PageWithTheme')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_tag', to='content.ThemeTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newspage',
            name='newsbase_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.NewsBase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicpage',
            name='pagewiththeme_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.PageWithTheme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicpage',
            name='themes',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='A comma-separated list of tags.', through='content.TaggedTheme', to='content.ThemeTag', verbose_name='Tags'),
        ),
    ]
