# Generated by Django 3.0.7 on 2020-09-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20200925_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='excluded_phrases',
            field=models.CharField(blank=True, help_text='Excluded keywords and phrases', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='pinned_phrases',
            field=models.CharField(blank=True, help_text='Pinned keywords and phrases', max_length=255, null=True),
        ),
    ]
