# Generated by Django 3.0.7 on 2020-08-04 09:39

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20200804_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpage',
            name='themes',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='A comma-separated list of tags.', through='content.TaggedTheme', to='content.ThemeTag', verbose_name='Themes'),
        ),
    ]
