# Generated by Django 3.0.7 on 2020-09-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20200925_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='body_no_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
