# Generated by Django 3.0.7 on 2021-02-07 11:02

from django.db import migrations
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_increase_wagtail_file_field_length_01022021_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="footer_documents",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "footer_document_list_item",
                        wagtail.documents.blocks.DocumentChooserBlock(
                            help_text="Show a list of documents at the end of the page"
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
