# Generated by Django 3.0.7 on 2020-08-04 11:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20200804_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('topic_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.TopicPage')),
                ('topic_page_test', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_topics', to='content.Guidance')),
            ],
            options={
                'verbose_name': 'Topics',
                'verbose_name_plural': 'Topics',
                'abstract': False,
            },
        ),
    ]
