# Generated by Django 3.0.7 on 2020-10-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_contentpage_body_no_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='search_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
