# Generated by Django 3.1.6 on 2021-02-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_contentpage_footer_documents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpage",
            name="footer_documents",
        ),
    ]
