# Generated by Django 3.0.7 on 2020-08-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_topictest'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='content.TopicTest'),
            preserve_default=False,
        ),
    ]
