# Generated by Django 3.0.7 on 2020-08-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_policy_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='topictest',
            name='themes',
            field=models.ManyToManyField(to='content.ThemeTest'),
        ),
    ]
