# Generated by Django 3.1.8 on 2021-05-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0014_historicalsearchexclusionpagelookup_historicalsearchkeywordorphrase_historicalsearchpinpagelookup_hi",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsitealertbanner",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="SiteAlertBanner",
        ),
        migrations.DeleteModel(
            name="HistoricalSiteAlertBanner",
        ),
    ]
