# Generated by Django 3.1.6 on 2021-05-10 13:03

import content.blocks
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_historicalsearchexclusionpagelookup_historicalsearchkeywordorphrase_historicalsearchpinpagelookup_hi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsitealertbanner',
            name='banner_text',
            field=wagtail.core.fields.StreamField([('paragraph', content.blocks.TextBlock(blank=True, features=['ol', 'ul', 'link', 'document-link', 'anchor-identifier']))]),
        ),
        migrations.AlterField(
            model_name='sitealertbanner',
            name='banner_text',
            field=wagtail.core.fields.StreamField([('paragraph', content.blocks.TextBlock(blank=True, features=['ol', 'ul', 'link', 'document-link', 'anchor-identifier']))]),
        ),
    ]
