# Generated by Django 3.2.17 on 2023-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_auto_20210521_0957"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalsearchexclusionpagelookup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical search exclusion page look up",
                "verbose_name_plural": "historical search exclusion page look ups",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsearchkeywordorphrase",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical search keyword or phrase",
                "verbose_name_plural": "historical search keyword or phrases",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsearchpinpagelookup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical search pin page look up",
                "verbose_name_plural": "historical search pin page look ups",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltheme",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical theme",
                "verbose_name_plural": "historical themes",
            },
        ),
        migrations.AlterField(
            model_name="historicalsearchexclusionpagelookup",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsearchkeywordorphrase",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsearchpinpagelookup",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltheme",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
