# Generated by Django 4.1.9 on 2023-06-07 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("networks", "0002_network_excerpt"),
        ("content", "0018_remove_contentpage_body_no_html_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE content_contentpage AS cp SET search_excerpt = (SELECT excerpt FROM networks_network AS nn WHERE nn.contentpage_ptr_id = cp.basepage_ptr_id);",
            reverse_sql="UPDATE networks_network AS nn SET excerpt = (SELECT search_excerpt FROM content_contentpage AS cp WHERE nn.contentpage_ptr_id = cp.basepage_ptr_id);"
        ),
        migrations.RemoveField(
            model_name="network",
            name="excerpt",
        ),
    ]
