# Generated by Django 4.1.9 on 2023-06-07 12:15

from django.db import migrations


def copy_excerpts_to_parent(apps, schema_editor):
    Network = apps.get_model("networks", "Network")
    for network in Network.objects.filter(excerpt__isnull=False):
        network.search_excerpt = network.excerpt
        network.save()


def copy_excerpts_from_parent(apps, schema_editor):
    Network = apps.get_model("networks", "Network")
    for network in Network.objects.all():
        network.excerpt = network.search_excerpt
        network.save()


class Migration(migrations.Migration):
    dependencies = [
        ("networks", "0002_network_excerpt"),
        ("content", "0018_remove_contentpage_body_no_html_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_excerpts_to_parent, copy_excerpts_from_parent),
        migrations.RemoveField(
            model_name="network",
            name="excerpt",
        ),
    ]
