# Generated by Django 4.1.10 on 2023-10-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peoplefinder", "0118_alter_person_email"),
        ("networks", "0003_remove_network_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="content_contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="content_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peoplefinder.person",
            ),
        ),
    ]
