# Generated by Django 4.2.17 on 2025-01-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0044_alter_contentpage_description"),
        ("peoplefinder", "0123_ukstafflocation_building_name"),
        ("networks", "0004_network_content_contact_email_network_content_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkContentPage",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentpage",
                    ),
                ),
                (
                    "content_contact_email",
                    models.EmailField(
                        help_text="Contact email shown on article, this could be the content owner or a team inbox",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "content_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="peoplefinder.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.contentpage", models.Model),
        ),
    ]
