# Generated by Django 4.2.17 on 2025-01-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0005_networkcontentpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="network_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dbt_initiatives", "DBT Initiatives"),
                    ("department_function", "Department/Function"),
                    ("diversity_and_inclusion", "Diversity and Inclusion"),
                    ("health_and_wellbeing", "Health and Wellbeing"),
                    ("interests_and_hobbies", "Interests and Hobbies"),
                    (
                        "professional_development_and_skills",
                        "Professional Development and Skills",
                    ),
                    ("social_and_community", "Social and Community"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
