# Generated by Django 5.1.5 on 2025-02-10 14:11

from django.db import migrations, models


def update_network_type(apps, schema_editor):
    Network = apps.get_model("networks", "Network")
    Network.objects.filter(network_type="professional_development_and_skills").update(
        network_type="professional_networks_and_skills"
    )


def rollback_network_type(apps, schema_editor):
    Network = apps.get_model("networks", "Network")
    Network.objects.filter(network_type="professional_networks_and_skills").update(
        network_type="professional_development_and_skills"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0007_alter_network_network_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="network_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dbt_initiatives", "DBT Initiatives"),
                    ("department_function", "Department/Function"),
                    ("diversity_and_inclusion", "Diversity and Inclusion"),
                    ("health_and_wellbeing", "Health and Wellbeing"),
                    ("interests_and_hobbies", "Interests and Hobbies"),
                    (
                        "professional_networks_and_skills",
                        "Professional Networks and Skills",
                    ),
                    ("social_and_community", "Social and Community"),
                    ("volunteering", "Volunteering"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(update_network_type, rollback_network_type),
    ]
