# Generated by Django 5.1.5 on 2025-02-10 14:11

from django.db import migrations, models

OLD_NETWORK_TYPE = "professional_development_and_skills"
NEW_NETWORK_TYPE = "professional_networks_and_skills"


def update_network_type_for_page_and_revision(
    network_page, old_network_type: str, new_network_type: str
):
    if network_page.network_type == old_network_type:
        network_page.network_type = new_network_type
        network_page.save(update_fields=["network_type"])

    for revision in network_page.revisions.all():
        if revision.content["network_type"] == old_network_type:
            revision.content["network_type"] = new_network_type
            revision.save(update_fields=["content"])



def update_network_type(apps, schema_editor):
    Network = apps.get_model("networks", "Network")

    for network in Network.objects.all():
        update_network_type_for_page_and_revision(
            network,
            OLD_NETWORK_TYPE,
            NEW_NETWORK_TYPE,
        )


def rollback_network_type(apps, schema_editor):
    Network = apps.get_model("networks", "Network")

    for network in Network.objects.all():
        update_network_type_for_page_and_revision(
            network,
            NEW_NETWORK_TYPE,
            OLD_NETWORK_TYPE,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0007_alter_network_network_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="network_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dbt_initiatives", "DBT Initiatives"),
                    ("department_function", "Department/Function"),
                    ("diversity_and_inclusion", "Diversity and Inclusion"),
                    ("health_and_wellbeing", "Health and Wellbeing"),
                    ("interests_and_hobbies", "Interests and Hobbies"),
                    (
                        "professional_networks_and_skills",
                        "Professional Networks and Skills",
                    ),
                    ("social_and_community", "Social and Community"),
                    ("volunteering", "Volunteering"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(update_network_type, rollback_network_type),
    ]
