# Generated by Django 5.1.5 on 2025-02-21 12:10

from django.db import migrations, models

OLD_NETWORK_TYPE = "social_and_community"
NEW_NETWORK_TYPE = "social_and_sports"


def run_network_type_update(apps, old_network_type, new_network_type):
    Network = apps.get_model("networks", "Network")
    Revision = apps.get_model("wagtailcore", "Revision")

    for network_page in Network.objects.all():
        if network_page.network_type == old_network_type:
            network_page.network_type = new_network_type
            network_page.save(update_fields=["network_type"])

        revisions = Revision.objects.filter(
            content_type_id=network_page.content_type.id, object_id=network_page.id
        )
        for revision in revisions:
            if revision.content["network_type"] == old_network_type:
                revision.content["network_type"] = new_network_type
                revision.save(update_fields=["content"])


def update_network_type(apps, _):
    run_network_type_update(
        apps,
        OLD_NETWORK_TYPE,
        NEW_NETWORK_TYPE,
    )


def rollback_network_type(apps, _):
    run_network_type_update(
        apps,
        NEW_NETWORK_TYPE,
        OLD_NETWORK_TYPE,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0008_alter_network_network_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="network_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dbt_initiatives", "DBT Initiatives"),
                    ("department_function", "Department/Function"),
                    ("diversity_and_inclusion", "Diversity and Inclusion"),
                    ("health_and_wellbeing", "Health and Wellbeing"),
                    ("interests_and_hobbies", "Interests and Hobbies"),
                    (
                        "professional_networks_and_skills",
                        "Professional Networks and Skills",
                    ),
                    ("social_and_sports", "Social and Sports"),
                    ("volunteering", "Volunteering"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(update_network_type, rollback_network_type),
    ]
