# Generated by Django 3.0.7 on 2020-10-29 09:07

import django.db.models.deletion
from django.db import migrations, models

import content.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("working_at_dit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "pagewithtopics_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="working_at_dit.PageWithTopics",
                    ),
                ),
                ("redirect_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("working_at_dit.pagewithtopics",),
        ),
        migrations.CreateModel(
            name="ToolsHome",
            fields=[
                (
                    "contentpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.ContentPage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("content.contentpage",),
        ),
    ]
