# Generated by Django 3.0.7 on 2020-09-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200813_1142'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolshome',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='toolshome',
            name='contentpage_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ContentPage'),
            preserve_default=False,
        ),
    ]
