# Generated by Django 3.0.7 on 2020-09-02 09:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_linklistitem'),
        ('tools', '0002_auto_20200902_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsHomeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_item_tool_home', to='content.LinkListItem')),
                ('tool_home', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_home_link_items', to='tools.ToolsHome')),
            ],
            options={
                'unique_together': {('tool_home', 'link_item')},
            },
        ),
    ]
