# Generated by Django 3.0.7 on 2020-10-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0002_auto_20201029_1214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="redirect_url",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
