# Generated by Django 3.0.7 on 2020-09-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_toolshomelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ToolsHomeLink',
        ),
    ]
