name: "Update Requirements"

on:
  push:
    branches:
      - "dependabot**"

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Generate requirements
        run: |
          poetry export --without-hashes --output requirements.txt
      - name: Commit requirements.txt
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated update of requirements.txt"
          git push
