name: "Dependabot Requirements"

on:
  pull_request:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install poetry
      - run: git checkout HEAD
      - name: Generate requirements
        run: |
          poetry export --without-hashes --output requirements.txt
      - name: Commit requirements.txt
        continue-on-error: true
        run: |
          git config user.name 'GitHub Actions'
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automated update of requirements.txt"
          git push
      - run: echo "Making a successful exit code so we don't block the merge"
